### ISSUE TITLE
Unable to download my file

### ISSUE THREAD

**Issue by grysor** [sblask/webextension-skip-redirect#101]
Hello
i have a desktop pc and am under windows10 pro 64 bits
Here is my big problem:
With the google chrome browser, when I go on this link:
https://shortmony.me/MxJ15
and validate all the captchas, in the end I get the file named "code.txt" which is 50 bytes.

-But with the browser firefox, when I open this same link, pages of ads open and I never have the file "code.txt" at the end because it opens me pages of ads instead .

-and when I add your extension "skip redirect" to firefox, the captchas and countdowns of my link succeed one another infinitely, and I never get my file "code.txt".
can you fix this bug please? thank you in advance

**Comment by sblask** [comment]
If it doesn't work with Skip Redirect disabled I can't do anything, because disabling it would have been my suggestion.

**Comment by grysor** [comment]
hello thanks for your answer :)
yes it does not work with skip redirect.
What I do not understand is that I have ublock on chrome and also on firefox with the same ticked boxes for 2
my opinion is that chrome is better configured originally to block redirects to ad sites than firefox.

I also specify that I have no virus on my computer, I avast and malwarebytes and I perform annalyses every week, and I have no virus.Mon firefox is also up to date in the latest version.
-Your extension "skip redirect" for firefox is almost perfect because it makes me avoid the sites of ads in the link that I posted and shows me that the captchas, which is normal, but a pity it bug while doing succeed the captchas to infinity and that I never get the file "code.txt" :(

but it works under chrome each time and I get this file "code.tx"
I wish you good luck :) if one day you find the solution for my problem, thank you
