### ISSUE TITLE
big bug on google translate

### ISSUE THREAD

**Issue by grysor** [sblask/webextension-skip-redirect#102]
Hello
I have a pc desktop with windows10 pro 64bit up to date
-I am under firefox quantum 62.0
-I have extension skip redirect 2.2.1

Google translate no longer wants to translate web pages in english to french !!! :(
the page stays in english all the time :(
-I have tried everything : refresh google translate several times, or restart firefox but the problem is still there
And as soon as I disable the skip redirect extension, then reload google translate, this time my link translates from english to french.

I have tried several times by disabling and reactivating the extention and it is good skip redirect that prevents translate web pages by google translate!

can you fix this problem please?

**Comment by sblask** [comment]
You have to add google translate to the blacklist so skip redirect doesn't do anything.

**Comment by crssi** [comment]
this is what i have: `translate.google.com/`

and this is my complete list:
```
/abp
/account
/auth
/cookie
/download
/login
/logoff
/logon
/logout
/oauth
/preferences
/profile
/register
/signin
/signoff
/signon
/signout
/signup
/subscribe
/verification
action=login
/adfs/ls/
https://archive.is/
https://chart.googleapis.com/chart
https://web.archive.org/
https://webcache.googleusercontent.com/cred_submit
/_login
logout=
medium.com/
microsofttranslator.com/
/openid/
paypal.com/
rover.ebay.co
securityheaders.com/
/saml/
/SAML2/
_sso=
/sso/
t.umblr.com/redirect
translate.google.com/
virustotal.com/
/websso/
/wsfederation
youtube.com/embed/
ssllabs.com/
i-dont-care-about-cookies.eu/
```

Cheers
