### ISSUE TITLE
Sign in doesn't work in https://bugs.chromium.org 

### ISSUE THREAD

**Issue by NN---** [sblask/webextension-skip-redirect#103]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Pressing sign in in https://bugs.chromium.org/ redirects page back.
After disabling Skip Redirect sign in works.

**Comment by sblask** [comment]
You need to add it to the blacklist.
