### ISSUE TITLE
redirection on amazon and other sites does not work!

### ISSUE THREAD

**Issue by grysor** [sblask/webextension-skip-redirect#104]
Hello
I have a pc desktop with windows10 pro 64bit up to date
-I am under firefox quantum 62.0.2
-I have extension skip redirect 2.2.1

all links amazon, cdiscount, la redoute, posted by users on these 2 pages do not work! redirects on these links do not work  :
https://www.dealabs.com/bons-plans/fauteuil-de-bureau-akracing-nitro-blanc-noir-ou-rouge-noir-1307187?page=2#thread-comments

can you fix this bug please? thank you in advance

**Comment by sblask** [comment]
You'll need to add www.dealabs.com to your blacklist.
