### ISSUE TITLE
Breaks reddit search and submission process

### ISSUE THREAD

**Issue by dotdapple** [sblask/webextension-skip-redirect#105]
**Firefox 62.0.2 (64-bit) • macOS (10.13.6) • Skip Redirect 2.2.1**

- [x] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] The issue is not about adding entries to the default blacklist

### Description

I tried posting this Wikipedia article to reddit…

`https://en.wikipedia.org/wiki/Room_641A`

It was previously posted, so reddit took me to that previous post, where its URL looked like…

`https://www.reddit.com/r/wikipedia/comments/73f3ze/room_641a/?submit_url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FRoom_641A&already_submitted=true&submit_title=Room+641A+-+Wikipedia`

Skip Redirect misinterpreted the URL and directed me to the Wikipedia article instead of that reddit post.

Then I tried searching for the Wikipedia article’s URL on reddit, which typically sends me to the following search results page…

`https://www.reddit.com/submit?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FRoom_641A`

…but Skip Redirect also misinterpreted this, sending me to the Wikipedia article instead of that search results page.

For now I have `https://www.reddit.com/` blacklisted/exempted from being skipped, though I was wondering if there’s better a way to solve this.

**Comment by sblask** [comment]
Skip Redirect works just as expected. You can try to blacklist only `submit`, but otherwise blacklisting reddit is the way to go.

**Comment by dotdapple** [comment]
Thanks for the response sblask.
