### ISSUE TITLE
Unable to "Report Deceptive Site" in Firefox

### ISSUE THREAD

**Issue by campbellkerr** [sblask/webextension-skip-redirect#107]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] The issue is not about adding entries to the default blacklist

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)
 - Not sure if this violates any of the "New Issue Checklist" items - sorry if it does!

When I come across a sketchy site, go Help, Report Deceptive Site, Skip Redirect stops the feature from going any further and I'm unable to report the site as deceptive. Disabling the extension fixes this.

URL - please don't enter any personal info: https://dal-shared-34.hostwindsdns.com/~ghgehrmt/log-in/mmp/webapps/identity.php

![image](https://user-images.githubusercontent.com/38451588/47357207-d2737d00-d711-11e8-9d52-722cbffe0d89.png)

![image](https://user-images.githubusercontent.com/38451588/47356974-43666500-d711-11e8-9062-8f33f590fb0b.png)

**Comment by sblask** [comment]
Add the mozilla URL to your blacklist.
