### ISSUE TITLE
No longer available in chrome store...

### ISSUE THREAD

**Issue by rugabunda** [sblask/webextension-skip-redirect#108]
They updated their security policy for extensions along with the latest rollout of chrome 70 stable. They no longer allow obfuscated code in extensions.

https://www.engadget.com/2018/10/01/google-chrome-extensions-privacy-safety-security/
https://www.v3.co.uk/v3-uk/news/3063844/google-to-improve-security-of-extensions-in-chrome-70
https://www.theregister.co.uk/2018/10/02/google_chrome_web_store/

Is this why it is no loner available in Chrome Store? https://chrome.google.com/webstore/detail/jaoafjdoijdconemdmodhbfpianehlon

**Comment by sblask** [comment]
I wasn't aware that the extension was taken down, didn't get an email about it and there is no information in my dashboard apart from a big fat red "Taken Down". It says I can't publish because at least one screenshot or video is required. I'll try adding one...

**Comment by rugabunda** [comment]
Given Google/youtube's censorship of late, perhaps they are crackin' down on anything that can impede on their data gathering.

**Comment by rugabunda** [comment]
An extension to bypass chrome store & install extensions via github would be great :)

**Comment by sblask** [comment]
When I tried to publish it after adding  a screenshot I just got a generic error. Tried to contact them but didn't get an answer yet.

Not sure such an extension is possible, but you can always clone the repo, go to your extension settings, enable developer and then click on `Load unpacked` and point to clone...

**Comment by rugabunda** [comment]
Wow I was unaware of this! I downloaded your extension and was expecting an xpi file. But wasn't aware of using 'unpacked' extensions. Thanks for the tip.

**Comment by rugabunda** [comment]
I had just came across this since I had previously commented... https://adnauseam.io/free-adnauseam.html

**Comment by sblask** [comment]
Just got an email. They did a review and put Skip Redirect back. No reasoning given. Thanks for bringing this to my attention, I don't think I would have noticed otherwise!

**Comment by rugabunda** [comment]
OK its finally back. could you let us know what happened? Thanks brother!

**Comment by rugabunda** [comment]
Oh you already commented! OK great news!
