### ISSUE TITLE
Wrong redirect on weibo

### ISSUE THREAD

**Issue by OpportunityLiu** [sblask/webextension-skip-redirect#110]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [ ] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

For url 
https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2Ftv%2Fv%2FHg4ICf1ZD%3Ffid%3D1034%3A4338313847594844&domain=.weibo.com&sudaref=https%3A%2F%2Fbbs.saraba1st.com%2F2b%2Fthread-1809748-6-1.html&ua=php-sso_sdk_client-0.6.28&_rand=1550653835.7898

The expected target is https://weibo.com/tv/v/Hg4ICf1ZD?fid=1034:4338313847594844 (the `url` parameter). In actual, https://bbs.saraba1st.com/2b/thread-1809748-6-1.html (the `sudaref` parameter) is used, which is the referrer of the link.

**Comment by sblask** [comment]
There are plenty of similar issues. TLDR: nothing can be done about it.

**Comment by crssi** [comment]
@OpportunityLiu in you case you could add for example `domain=.weibo.com&sudaref=` into `Blacklist`

Cheers
