### ISSUE TITLE
Extension does not remove Reddit's onclick URL tracking.

### ISSUE THREAD

**Issue by Crypto-Nym** [sblask/webextension-skip-redirect#111]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates
- [x ] I can reproduce the problem on the latest stable version (not nightly!)
- [x ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x ] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [x ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)

Reddit uses code to rewrite the destination URL when it is clicked to include various tracking parameters.  The link looks fine when moused over, but upon clicking and releasing the mouse button, extra data is inserted into the URL.

For example if I click a link in a subreddits sidebar to (say), https://old.reddit.com/r/cats/  the code adds several parameters to the link usually starting with utm_souce,  after Reddit processes the link it re-adjusts the URL back to the original clicked link.

Obviously for this is not desired activity from a privacy PoV.

**Comment by crssi** [comment]
This extension is not meant to remove URL parameters, but to skip redirection.
Skip redirection means to remove visiting tracking domain.
Lets say you click on a link that leads you to URL like `https://trackingdomain.com/?redirectto=https://interestingdomain.com`, then this extension will remove the tracking domain and lead you directly to domain/URL of your interest avoiding the tracking domain.
In the example case the destination domain URL will be rewritten to `https://interestingdomain.com`

If you wish to remove some (tracking) URL parameters you need to install another extension for that purpose. There are two good one:
1. [Neat URL](https://addons.mozilla.org/firefox/addon/neat-url/)
2. [ClearURLs](https://addons.mozilla.org/firefox/addon/clearurls/)

The first one gives you option for fine tuning, and the second one is fully automatic.
I am using both of those and the `Skip Redirect` too.

Cheers

**Comment by ilikenwf** [comment]
@crssi but that's exactly what reddit does:

https://out.reddit.com/t3_e3usyk?url=https%3A%2F%2Fnow.tufts.edu%2Farticles%2Fbacteria-help-make-low-calorie-sugar&token=AQAAHtPiXUptvPtZuaqZXqhbQDNdwSRo_hbkTWwWguYmSMuR9gCt&app_name=reddit.com

**Comment by crssi** [comment]
@ilikenwf 
Where does this come from?
Is this sample from location and time when this issue was opened?

**Comment by ilikenwf** [comment]
The out.reddit.com link came from a reddit news article today.

If one is logged in they can disable these links, however people who
don't login to reddit still get funneled through the tracking area...

So while this ticket is old, I'd argue it is still valid...

**Comment by crssi** [comment]
I don't see where you see a problem?
What result do you expect when you click on a link you have provided?

Important note: I am not an developer of this extension, so I can speak only for my self and I am just trying to help 😉 .

**Comment by sblask** [comment]
@ilikenwf I just tried your link, I go to https://now.tufts.edu/articles/bacteria-help-make-low-calorie-sugar directly without passing through out.reddit. So this is where this extensions works as intended. The original problem described in the issue was URL parameters being added by reddit which were expected to be removed by this extension, but it's out of scope. If you've got another problem, please open a new issue.
