### ISSUE TITLE
Blacklist with exceptions, possible?

### ISSUE THREAD

**Issue by ReporterX** [sblask/webextension-skip-redirect#113]
1 . Some sites use `/pc_search` and `/search` in the search result. The redirects are undesirable so I put this in the blacklist.
```
\/(pc_)?search
```

However this will also ignore redirect links in Firefox addons site whose addons' names start with search. For example, 

https://outgoing.prod.mozaws.net/v1/3949e3fa1f8684e62e12b49707af540aec3f7eef13e37789e3ab33c8ae3ab05a/https%3A//github.com/andreicristianpetcu/Search-and-Switch-Containers

https://outgoing.prod.mozaws.net/v1/409bf55345207cc65f09ea6142e4b4cd069323e76f635076bfc139da6d46de4d/https%3A//github.com/dessant/search-by-image

The format of redirect links which I still want to execute: 
https://outgoing.prod.mozaws.net/vX/XXXXXXXXXX/https%3A// (domain name)/...

It would be great if I can specify something like this:
```
\/(pc_)?search | except at mozaws.net
```

2 . Is positive/negative lookbehind/lookahead supported?

Thank you.

**Comment by crssi** [comment]
`\/(pc_)?search=` :wink: 
Do you have any sample URLs to share? (not the Mozilla ones, but the opposite)

**Comment by ReporterX** [comment]
https://www.google.com/search?q=
https://image.baidu.com/n/pc_search?queryImageUrl=https%3A%2F%2Funitedwithisrael.org%2Fwp-content%2Fuploads%2F2014%2F11%2Fhappy.jpg&fm=index&uptype=paste

**Comment by sblask** [comment]
How many search sites do you use? Why not just be specific and blacklist `www.google.com/search`? Otherwise, something like this: https://stackoverflow.com/questions/6851921/negative-lookahead-regular-expression could work?

**Comment by ReporterX** [comment]
Google is not just one of them. I found there are various sites which uses `/search/`. It seems to be quite common for search queries.

Thanks for the pointer. This regex works.
```
http(s)?:\/\/(?!outgoing\.prod\.mozaws\.net).*\/(pc_)?search
```

BTW you might consider putting this in the default list.
```
/searchbyimage
```
