### ISSUE TITLE
Toggle on/off is possible if we change a bit

### ISSUE THREAD

**Issue by ReporterX** [sblask/webextension-skip-redirect#114]
Currently the options are:
( ) Off
( ) Skip all redirects except for URLs matching any of the lines in the blacklist.
　[ ] Skip redirects for URLs with the same public domain
( ) Skip redirects only for URLs matching any of the lines in the whitelist.

If it is changed into: 
### Status
( ) On
( ) Off

### Mode
( ) Skip all redirects except for URLs matching any of the lines in the blacklist.
　[ ] Skip redirects for URLs with the same public domain
( ) Skip redirects only for URLs matching any of the lines in the whitelist.

You don't keep changing the mode you use, but you want to switch it off in some cases since it can generate false positives.

Then perhaps we can assign a customizable shortcut key to toggle on/off.
Or left click to toggle on/off, right click to select the menu to open the popup.

Another idea is to put the toggle at the top right corner of the popup. The toggle will be something like this: 
![screenshot 1](https://user-images.githubusercontent.com/8235338/56497150-026bd380-652f-11e9-9398-44aaa0a72f9f.jpg)

Once you open the popup, the toggle is closest to your mouse pointer. Faster and easier to toggle it on/off.

The popup: 

._________________[toggle icon]
|
|
|
|____________________________

**Comment by sblask** [comment]
This has been discussed before, won't do it.
