### ISSUE TITLE
Prevent redirects for GitHub repos with URL name

### ISSUE THREAD

**Issue by kevinpapst** [sblask/webextension-skip-redirect#115]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

I start off with a big THANK YOU for sharing this nice extension 👍 

And I am pretty sure this is a no-brainer for you, but I tried several attempts in blacklisting, but none worked as expected.

I want to prevent being redirected for GitHub repos that are named like their URL:
https://github.com/kimai/www.kimai.org (I can't access the repo)

But at the same time I want to be able to click links in my GitHub notification emails (which Gmail seems to hijack):
https://www.google.com/url?q=https://github.com/kevinpapst/kimai2/pull/815?email_source%3Dnotifications%26email_token%3DAAECFKT525YRT4IG3AWQVHLPZKPM5A5CNFSM4HP6Z2QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXGSI5Q%23issuecomment-499983478&source=gmail&ust=1560019856365000&usg=AFQjCNFqGhk-hMXXKoF3jovs42cQwLAJGg

If I use a blacklist entry like `^https:\/\/github\.com\/` I can see the repo, but the URL redirect is not prevented. Seems I either completely misunderstand the blacklist feature or the regexp is wrong.

Can you help me out?

**Comment by sblask** [comment]
I just tried your regexp in Chrome and it works just fine, your first link is loads the github page just fine the second goes straight to the github page, skipping google. Can you try again?

**Comment by kevinpapst** [comment]
Believe me, I try many things before I annoy other devs with noob questions ;-) 
So, yes, I remove the rule, added it again and yes, I can access the repository. (that worked before) But the google redirect is still happening - and the google redirects are obviously one of the main reasons for using the plugin...

Maybe my settings are wrong? I'd say default installation with just that one addional rule:
<img width="793" alt="Bildschirmfoto 2019-06-07 um 23 11 59" src="https://user-images.githubusercontent.com/533162/59133931-ddfe7600-8979-11e9-9c68-442c0391e0e4.png">

**Comment by kevinpapst** [comment]
Hmpffff .... "have you tried turning it off an on again"? 

After you said it works on your end I removed the extension, restarted FF, installed the extension, added my regexp, restarted FF again => now it works 

Noobs at work 🤣 Sorry for wasting your time!
