### ISSUE TITLE
wrong redirect

### ISSUE THREAD

**Issue by halcion** [sblask/webextension-skip-redirect#120]
### What is your browser?

- [ ] Chrome 75

### What is your operating system?

- [ ] Linux android 7
- [ ] Windows 7

### Description (please include examples/screenshots where applicable)

If the link ends with "referrer=h..ps://x" then skip redirect loads "h..ps://x" the referrer instead of the site that it's supposed to go to

**Comment by crssi** [comment]
Generally this is expected and desired result.
In your case you should whitelist the target domain (I don't mean the  referer domain).
Can you share a working sample?
