### ISSUE TITLE
Tradedoubler links not skipped

### ISSUE THREAD

**Issue by Mirellanmawl** [sblask/webextension-skip-redirect#122]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [X] The issue is not about adding entries to the default blacklist

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)

Skip Redirect not redirect Tradedoubler links.
Example:
`http://clk.tradedoubler.com/click?p(21)a(2513392)g(17284614)url(https://www.adlibris.com/se/sok/?q=9789173133609)`

It partly works since the link above redirects to a link to:
`https://redir.tradedoubler.com/projectr/?utm_source=tradedoubler*_td_*KEEP_NEWEST&utm_medium=affiliate*_td_*KEEP_NEWEST&utm_campaign=boktugg.se*_td_*KEEP_OLDEST&tduid=5dbbf313d3ce266efccc429bf2769995&_td_deeplink=https://www.adlibris.com/se/sok/?q=9789173133609`
and _that_ link is skipped. So it is like a double redirection. But I would like to see the clk.tradedoubler.com link also skipped.

**Comment by sblask** [comment]
There is no simple way of doing this without imlementing a special case that in turn might break other things. All that because they invented their own way of handling query parameters. So I won't do it.
