### ISSUE TITLE
multiple redirects not being skipped

### ISSUE THREAD

**Issue by 3rdventricle** [sblask/webextension-skip-redirect#123]
### What is your browser?

- [X ] Firefox
- [ X] Chrome

### What is your operating system?

- [ X] Linux
- [ ] Mac
- [ X] Windows

### Description (please include examples/screenshots where applicable)

https://slickdeals.net/?adobeRef=d165fa54c36111e9b13be2ff9c0aef190003&sdtid=13320496&sdpid=129827077&sdfid=9&lno=1&trd=https%20brickseek%20com%20lowes%20inven%20&pv=&au=&sdtrk=featured&prop=pfd-13320496%7Cprt-3&u2=https%3A%2F%2Fbrickseek.com%2Flowes-inventory-checker%2F%3Fsku%3D50041370

When I click on any link from that site it usually has the correct URL at the end but it dead ends at their affiliate link site because of a domain black list on the router.
What I would like to see, is the option to extract the last URL in the list from this domain.
I generally just copy the link, and decode the percents to characters, then copy that and decode again, and get a good copy-able link. Then I cut the last URL off and go to that site.
It is a lot of work and I was wondering if skip redirect is capable of doing this automatically?
Thank you for your time.

**Comment by sblask** [comment]
I just tried, clicked on your link and it goes straight to `https://brickseek.com/lowes-inventory-checker/?sku=50041370` So Skip Redirect works as intended.
