### ISSUE TITLE
Options menu too wide

### ISSUE THREAD

**Issue by nbayle** [sblask/webextension-skip-redirect#124]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
The options menu always looks like this on both my computers.

<img width="1926" alt="Screen Shot 2019-09-04 at 10 56 36" src="https://user-images.githubusercontent.com/8433050/64279283-8a151600-cf03-11e9-8993-3bc159429a02.png">

**Comment by sblask** [comment]
I believe this is a bug in Firefox and there is nothing I can do to fix it.
