### ISSUE TITLE
How to enter RE?

### ISSUE THREAD

**Issue by rubaboo** [sblask/webextension-skip-redirect#125]
How do I actually enter a regular expression into blacklist? do I need to `/enclose in shashes/` like a JS regex literal? If I simply enter the domain name, it works, but any attempt at a simplest RE fails. Please provide an example, say if I wanted to match the full URL and nothing else. Something like

```
/https:\/\/pinboard\.in$/
```

**Comment by sblask** [comment]
No enclosing slashes. I can't give an example because I don't know what you try to do. But the trailing $ is almost certainly wrong unless your URL is example.com/?redirectto=https://pinboard.in

**Comment by sblask** [comment]
I can give you an example that I have in my blacklist: `^https:\/\/github\.com\/` so any redirects on github are not skipped.
