### ISSUE TITLE
Google "I'm feeling lucky" redirect notice on reddit login

### ISSUE THREAD

**Issue by ruocco** [sblask/webextension-skip-redirect#126]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [X] The issue is not about adding entries to the default blacklist

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [X] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Google has recently started to [notice its users that they are being redirected](https://support.google.com/websearch/thread/15794018?hl=en) somewhere when using the feature "I'm feeling lucky".

"Skip-redirect" fixes this new behaviour for most of the query except for when trying to access the reddit login page.

How to reproduce:
Click here and see that instead of going directly to reddit login page you have the "you are being redirected" advice, even with the skip-redirect addon installed: https://www.google.com/url?q=https://www.reddit.com/login&BtnI=1

**Comment by sblask** [comment]
`login` is on the default blacklist. You can remove it there. but that might break many other pages.
