### ISSUE TITLE
Feature request: follow the original URL

### ISSUE THREAD

**Issue by crssi** [sblask/webextension-skip-redirect#127]
I am missing a helper for undesired skip redirect.
With that I mean some button/icon where click on it would lead you to the original link without skip.

Maybe right click on SR icon and option: follow the original link.
Actually I have no idea how to proceed, but something to chew on.

Cheers

**Comment by sblask** [comment]
There is no good way of doing this, but if someone else has an idea how to do it reliably, you can reopen.
