### ISSUE TITLE
I cannot download files from Google Drive

### ISSUE THREAD

**Issue by UniTechMaxed** [sblask/webextension-skip-redirect#131]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
Your extension keeps on skipping redirects in Google Drive so I can't download from the Google drive. I don't know why this happens but you can try it.

**Comment by sblask** [comment]
You ticked `If you have a problem a specific website: adding the domain to your blacklist does not solve the problem`, what exactly did you add to the blacklist?

**Comment by Mattwmaster58** [comment]
I had this exact same issue, adding `*.googleusercontent.*` to the blacklist solved the problem.
