### ISSUE TITLE
Long extension title on firefox breaks options layout

### ISSUE THREAD

**Issue by LDSpits** [sblask/webextension-skip-redirect#133]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Hello, I have an issue with the extension title where it pushes out the content from the extension completely to the left. This seems be caused by very long redirect url's
![image](https://user-images.githubusercontent.com/11315167/70633297-9f02f300-1c30-11ea-96af-4fa33c732ac8.png)
The length of this text has the following effect in the options menu
![image](https://user-images.githubusercontent.com/11315167/70633555-0a4cc500-1c31-11ea-93b3-5ca6d54c36b8.png)
This menu now takes up about 75% of my screen.

**Comment by sblask** [comment]
This is a duplicate. Not sure which number the other issue had. It's more a Firefox issue that it can't handle long title. Won't change the extension.
