### ISSUE TITLE
Does not stop site redirects

### ISSUE THREAD

**Issue by i4y** [sblask/webextension-skip-redirect#134]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [X] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [ ] The issue is not about adding entries to the default blacklist

### What is your browser?

- [ ] Firefox
- [X] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)

I added the site animehub.ac . At first it successfully stopped the popup sites but after consecutive clicks within the page, it no longer does it. The site was added to the blacklist.

**Comment by sblask** [comment]
You have to give more details here, otherwise I can't tell what you are trying to do and what is not working.

**Comment by dpastern** [comment]
Doesn't stop jbl.com redirecting to jbl.com.au.  I've tried turning off javascript (blanket, all sites), explicitly telling Chrome to not redirect for jbl.com or jbl.com.au; and your extension, and also the remove redirect everywhere extension too.  Nothing works.  AFAIK, the only way a site can redirect is via JS, cookies, a htaccess fire, or a redirect in DNS...getting very cranky!

**Comment by sblask** [comment]
@dpastern jbl.com uses an http redirect, nothing that can be circumvented because it happens server side.
