### ISSUE TITLE
Does not work well with blog hosted on Medium

### ISSUE THREAD

**Issue by dominhduc** [sblask/webextension-skip-redirect#135]
I tried to use the extension with a blog which is hosted on Medium, but it's not working.

Please use the extension to access this https://blog.zeplin.io/organizing-screens-in-zeplin-with-tags-128dc3ed0749 
then you'll see the problem.

**Comment by crssi** [comment]
Add `medium.com/` to blacklist. You can see here https://github.com/crssi/Firefox/blob/master/Skip_Redirect-Blacklist.txt

**Comment by ronjouch** [comment]
For searchability, what happens with Medium + custom domains + Skip Redirect is a "too-many-redirects" case, ending up with Firefox throwing the towel with error:

> The page isn’t redirecting properly
>
> An error occurred during a connection to blog.zeplin.io.
>
>    This problem can sometimes be caused by disabling or refusing to accept cookies.
