### ISSUE TITLE
Does not skip redirect

### ISSUE THREAD

**Issue by reblake** [sblask/webextension-skip-redirect#136]
### New Issue Checklist (tick off like this: `[x]`)

- [ X] I checked existing issues (open and closed) for possible duplicates
- [X ] I can reproduce the problem on the latest stable version (not nightly!)
- [X ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [ X] The issue is not about adding entries to the default blacklist

### What is your browser?

- [X ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X ] Windows

### Description (please include examples/screenshots where applicable)
Trying to access this web page (video is what I need to access).  
https://videos.support.samsung.com/installation/detail/videos/top-mount/video/5544171030001/top-mount-freezer-door-reversal?autoStart=true
I was able to access it before.  Now it just redirects to a log in, but this is wrong.  I need to load this original page.

**Comment by crssi** [comment]
If I try on some other browsers without any extensions, the result is the same.
Or your sample URL is not correct or this has nothing to do with this extension.
I am sure that if you disable this extension and visit your sample URL, the result will be the same.

Cheers

**Comment by sblask** [comment]
Closing this because of lack of feedback.

**Comment by reblake** [comment]
Sample URL is correct.  This extension is supposed to prevent re-directs.  Therefore, this extension should prevent the re-direct to a log-in page, and instead display the video.  Yes, of course, if I disable the extension and visit the URL I still get a re-direct.  This extension was supposed to solve that.  It doesn't, hence the issue.

**Comment by sblask** [comment]
If the video is protected by a login, how is this extension supposed to grant you access? Also, skipping URLs containing `login`(among others) is disabled because of just that, if you need to login, you need to login, skipping the login page would mean you are not logged in and hence have no access.
