### ISSUE TITLE
popjav.tv not work

### ISSUE THREAD

**Issue by kai456789** [sblask/webextension-skip-redirect#141]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates
- [x ] I can reproduce the problem on the latest stable version (not nightly!)
- [x ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x ] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)
https://popjav.tv/154164/un38340
download page not work

https://popjav.tv/download/?host=mixdrop&vid=33d485e4868774a533e43316
https://popjav.tv/download/?host=fileone&vid=d3d37736a75323367724a62613d48436139485e4

**Comment by sblask** [comment]
I don't think I can reproduce your problem. When in doubt, you can always add the domain of the download link to your blacklist.
