### ISSUE TITLE
Clear Facebook URL by remiving the 'fbclid' parameter

### ISSUE THREAD

**Issue by seth100** [sblask/webextension-skip-redirect#142]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

From facebook.com, would it be possible to remove the part about the `fbclid` query parameter?
E.g.

```
target.website.com/page?fbclid=IwUR7POFVnU4-U8klgvVfd4wC1exVN-4YFAGFNgACm4E32JiQ_FBWSbKnASZ4
```

to

```
target.website.com/page
```

Thank you!

**Comment by crssi** [comment]
Skip-Redirect isn't about removing parameters. 😉 
Try something like [Neat URL](https://addons.mozilla.org/firefox/addon/neat-url/)
