### ISSUE TITLE
Put icons into a folder?

### ISSUE THREAD

**Issue by Crystal-RainSlide** [sblask/webextension-skip-redirect#144]
### New Issue Checklist

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### Description

RT, which will make this repo more tidy.

**Comment by sblask** [comment]
Not really interested in doing this. I like to keep the same structure across all my repos. So I would have to move files and change scripts for all of them. I just don't feel the pain. And I am still waiting for Chrome to support svg icons and favicons which would improve things in general. Can't believe they are so far behind in that regard...
