### ISSUE TITLE
Popup doesn't work

### ISSUE THREAD

**Issue by DaiPero** [sblask/webextension-skip-redirect#145]
### New Issue!

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description:

"Enable Popup
Show notification for this many seconds (1 to 10)".

Popup doesn't work and never worked since Firefox 70/71.

**Comment by atomGit** [comment]
with Firefox on Linux i'm finding that the pop-up notification doesn't work reliably - while it displays normally for some sites, it displays only very briefly (100ms or so) for others - here is one example:

https://onezero.medium.com/how-to-totally-escape-ad-tracking-at-home-b2fadd34a991

**Comment by sblask** [comment]
I just tested this on Firefox 77 and it works fine for me. I am using Xubuntu 16.04. @atomGit I don't get a redirect with your medium URL so Skip Redirect doesn't do anything. I tried with www.google.com/chrome/?i-would-rather-use-firefox=http%3A%2F%2Fwww.mozilla.org/

**Comment by atomGit** [comment]
> I don't get a redirect with your medium URL so Skip Redirect doesn't do anything.

that's odd - in my case, with SR off, https://onezero.medium.com/how-to-totally-escape-ad-tracking-at-home-b2fadd34a991

redirects to...

https://onezero.medium.com/how-to-totally-escape-ad-tracking-at-home-b2fadd34a991?gi=sd

if i leave SR enabled, it redirects to an error page "The page isn’t redirecting properly"

**Comment by sblask** [comment]
I get the same redirect when I open the URL in an incognito window. But it's nothing that Skip Redirect handles, as there is no URL in the URL, so there is also no popup. I did however have proplem in the past on medium.com, don't remember what it was though.

**Comment by sblask** [comment]
As I said, works fine with my normal Firefox (78) install and when starting it clean using web-ext. Closing this now.
