### ISSUE TITLE
URL Parameter Blacklist

### ISSUE THREAD

**Issue by reubn** [sblask/webextension-skip-redirect#149]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

When URL parameters contain both `url=https://intended.com` and `ref=https://referrer.com`, the `ref` URL is often favoured - this results in the user being taken back to the page they came from - not being taken to the intended URL. This behaviour is inconsistent with the aim of this plugin.

Could a URL parameter blacklist be implemented, and contain common params that URLs should not be extracted from?

e.g.

```
ref
referrer
referer
from
source
... 
```

**Comment by IntelliMoo** [comment]
This behavior is also why I have to add .encReferrer= to the blacklist.

**Comment by sblask** [comment]
I think it's a good idea, but I don't think I have time to look into it. But maybe someone else? There is also the question of which URL parameters to have on the list. It's very hard to get right I think. And the last thing I'm wondering is, should this be a separate mode or in conjunction with either whitelist or blacklist mode. I don't think it should be a different mode, but what do you think?

**Comment by sblask** [comment]
Add this now, but it's not yet released. Will only work on Firefox 78 and later because it uses quite a recent addition. Chrome supports it for longer already.
