### ISSUE TITLE
Functionality to exclude affiliate links

### ISSUE THREAD

**Issue by Geineh** [sblask/webextension-skip-redirect#151]
Hi< Sebastian

WordPress has addon for referal links. Result of its work is hidden affiliate links

I found service which can decrypt / decode URLs
https://prozavr.ru/tools/rasshifrovka-korotkih-ssilok.php

So, if we will put link https://www.kobzarev.com/r/smmbox in service above we will get next:
https://www.kobzarev.com/r/smmbox/	https://smmbox.com/c/349271	https://smmbox.com/?utm_source=partner&utm_campaign=partner&utm_medium=partner

But page is only https://smmbox.com/

Can u add this funclionality 2 exclude this stupid refferal links?

### What is your browser?

- [ ] Chrome

### What is your operating system?

- [ ] Windows

### Description (please include examples/screenshots where applicable)

![image](https://user-images.githubusercontent.com/36577960/83088809-70bd8680-a09d-11ea-9fde-3e4d34c9e0e5.png)

**Comment by sblask** [comment]
Remove the `utm` stuff? That is not what this extension is for. You may want to look at https://chrome.google.com/webstore/detail/neat-url/jchobbjgibcahbheicfocecmhocglkco

**Comment by Geineh** [comment]
But your addon redirescts me to https://smmbox.com/?utm_campaign=partner

that's not right URL

**Comment by sblask** [comment]
SkipRedirect doesn't do anything with your URL, it's the website that does the redirect. Seems like  Neat URL does not remove stuff coming from redirects. When I reload  https://smmbox.com/?utm_campaign=partner the parameter is removed.

**Comment by Geineh** [comment]
tnx for answer. Have a nict day
