### ISSUE TITLE
skip youtu.be redirects

### ISSUE THREAD

**Issue by atomGit** [sblask/webextension-skip-redirect#152]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

please consider skipping youtube shortlinks (youtu.be)

the format is...

```
youtu.be/<string>
www.youtube.com/watch?v=<string>
```

**Comment by hyperfekt** [comment]
Seems like it's a bit out of scope for this extension - however I can recommend the Redirector extension to fulfill this job, it's very flexible.

**Comment by atomGit** [comment]
i'm actually using Redirector, but for those that don't need the functionality it provides, i thought this would be a good fit for yours since its job is to bypass the middle-man, which i think is exactly what youtu.be is, no?

**Comment by crssi** [comment]
Isn't the owner of `youtu.be` Google inc., as is for `youtube.com` ?
If so, then it isn't really a middle-man and its really just a shorthener.

**Comment by hyperfekt** [comment]
This extension decodes URLs encoded in other URLs. Constructing URLs from shared elements requires rewriting rules, a job that is better served by extensions meant to apply rewriting rules.

**Comment by atomGit** [comment]
understood
