### ISSUE TITLE
Whitelist Google Issue

### ISSUE THREAD

**Issue by ysamjo** [sblask/webextension-skip-redirect#153]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

First, thanks for the extension!

My Use Case: Google "I'm feeling lucky" is my default search engine when I type something in the addressbar. Worked flawlessly for several years, but now Chrome shows me a page like this:

https://www.google.com/url?q=https://de.wikipedia.org/wiki/James_Brown

When I enable your extension for every site, it works - the redirect page gets skipped.

But then I get other weird behaviour, but that's what the Whitelist mode is for, right? Regardless of what I put there, I can't get it to work for Google.

![Unbenannt](https://user-images.githubusercontent.com/26360094/83608557-60b21500-a57d-11ea-8f55-7833f0d7a000.png)

**Comment by sblask** [comment]
This: `https://*.google.com/url*` works. You are missing the `www` that Chrome hides by default and the path. This is not a regexp pattern like the blacklist.

Also see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

When trying out pattern, you also need to disable and enable skipping as otherwise changes are not applied :-( So you might have had it right at some point but you couldn't see the effect.

**Comment by ysamjo** [comment]
Yes, that does the job!

**Comment by johan456789** [comment]
@sblask Apparently `*://*.google.com.*/*` is an [invalid pattern](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#invalid_match_patterns). Is the only alternative is list all ccTLD that I use? Why is the syntax so strict?

**Comment by sblask** [comment]
@johan456789 I didn't come up with the syntax. Must be some browser internals.
