### ISSUE TITLE
Please add sync settings function

### ISSUE THREAD

**Issue by J4X0N** [sblask/webextension-skip-redirect#155]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

as title
please add sync settings function or cloudstore save settings
thanks a lot

**Comment by sblask** [comment]
No time to work on this at the moment, but maybe someone else has?
