### ISSUE TITLE
Problem with downloading from google.docs

### ISSUE THREAD

**Issue by Geineh** [sblask/webextension-skip-redirect#156]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] https://drive.google.com/file/d/0B6GaeaaoAPK1N2Q4WVBEVGp1dG8/view

### What is your browser?

- [ ] awesome Opera

### What is your operating system?
- [ ] Windows

**Comment by sblask** [comment]
Add  drive.google.com to the black list if it causes problems.
