### ISSUE TITLE
Please fix Mega decryption key problem.

### ISSUE THREAD

**Issue by IlyassKrichi** [sblask/webextension-skip-redirect#157]
### New Issue Checklist (tick off like this: `[x]`)

- [x] **I checked existing issues (open and closed) for possible duplicates**
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] **The issue is not about adding entries to the default blacklist**

### What is your browser?

- [ ] Firefox
- [ ] Chrome
- [x] **Microsoft Edge**
### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] **Windows**

### Description (please include examples/screenshots where applicable)
![Annotation 2020-06-13 225713](https://user-images.githubusercontent.com/65032700/84579837-46700680-adc9-11ea-8840-ce6bd9999640.png)
For example like this Mega URL, it used to be attached with its decryption code, but because of Skip Redirect, it have disappeared. I can tell because I have tried it without Skip Redirect.
**Thank you.**

**Comment by sblask** [comment]
Without the full URL I can't tell you much, but you probably need to add `mega.nz` to your blacklist.
