### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by molitar** [sblask/webextension-skip-redirect#161]
### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)

Link to picture does not redirect.

https://imagenpic.com/uobquuv4u9if/hari02p.jpg

Nothing happens sites there until I press to continue.

**Comment by sblask** [comment]
Skip Redirect doesn't work like that. If there is no URL in the URL it can't skip to it.
