### ISSUE TITLE
Not working on web.de basic

### ISSUE THREAD

**Issue by donkeyDau** [sblask/webextension-skip-redirect#163]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

I'm using web.de with the "basic" frontend (some other extension make web.de believe I'm using an outdated browser (haven't figured out yet which one but I'm fine with the basic)). web.de is re-writing all links in an email. So https://www.huawei.com/en/industry-insights/innovation/new-ipb becomes 
https://deref-web.de/mail/mobile/PvJkabLAoKg/deref/?redirectUrl=https%3A%2F%2Fwww.huawei.com%2Fen%2Findustry-insights%2Finnovation%2Fnew-ip I cannot make it work with skip-redirect.

My Blacklist:

- /abp
- /account
- /auth
- /cookie
- /download
- /login
- /logoff
- /logon
- /logout
- /oauth
- /preferences
- /profile
- /register
- /signin
- /signoff
- /signon
- /signout
- /signup
- /subscribe
- /verification
- 127.0.0.1
- kubernetes-dashboard
- www.zeit.de
- *.gitconnected.com

No entries in whitelist.

Version 2.2.3

Options:

- [x] Skip redirects for URLs with the same public domain
- [x] Skip all redirects except for URLs matching any of the lines in the blacklist. 

Am I using a wrong config or is it not working?

Thx!

**Comment by crssi** [comment]
Using wilcard `*` is quite "dangerous" in this case. Why is that only @sblask can explan.

Change the last one... that is `*.gitconnected.com` to `.gitconnected.com` and it will work.

Cheers

**Comment by sblask** [comment]
I think the wildcard just results in an exception, because it's not a valid regular expression. You probably want something like `.*\.gitconnected\.com` if you want more specific than `.gitconnected.com`.

**Comment by donkeyDau** [comment]
Thanks a lot. The wildcard was indeed the problem. I was more glob-ing than regexp-ing.

If it results in an exception I would vote for displaying this to the user. I assume it tried to get around infinite redirections on gitconnected.com and tried it with this "regexp" and it worked (obviously by breaking the whole extension).

**Comment by sblask** [comment]
I've had this request before, but if I don't want to make it too complicated, I can only show an error, like a red border, for the whole blacklist...

**Comment by donkeyDau** [comment]
I think this would be helpful. Couldn't you color the border of the box and display additionally a message like "Entry xy is causing exceptions. Please check it on https://regex101.com/ (or whatever site) for validity"?

**Comment by sblask** [comment]
I added a border and show the exception if there is a problem with the regular expression. To be released soon.

**Comment by donkeyDau** [comment]
Looks good. Thank you!
