### ISSUE TITLE
Breaks almost everything "Pay with PayPal" related

### ISSUE THREAD

**Issue by privacyguy123** [sblask/webextension-skip-redirect#164]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your blacklist does not solve the problem
- [ ] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Title says it all - would be nice to have pay with PayPal popup functionality while also having this addon installed.

**Comment by sblask** [comment]
I don't use Paypal so I can't tell, but you probably need to add `paypal` to the blacklist or use whitelist mode.

**Comment by crssi** [comment]
I am using `paypal.com/` in blacklist and never have a problem with paypal. 

Cheers
