### ISSUE TITLE
Facebook redirect to external websites

### ISSUE THREAD

**Issue by leifalbor** [sblask/webextension-skip-redirect#169]
Not an issue, just a question...

Facebook wraps its hyperlinks to external websites in a tracking string, i.e.:

https://l.facebook.com/l.php?u=https%3A%2F%2Flivinghistories.newcastle.edu.au%2Fnodes%2Fview%2F11191%3Ffbclid%3DIwAR02DxZKKFYZbmeWTolyTCxEPYEeaoA3Zexhc3UwZysKOIG1Yhp_lC36OT8&h=AT3Nx6gLcU9KeX1tx2FWJvJX_OhCwzh14wJTJJxJv3e4f95A9RbAprCMRCGccCVJuu4RYELwg3Haxw007ZeM_Eei9NL4Qssw-tAC8Yz8xYsRQSBhLIv_4oqp8YyCH1JaeO4JR8w8wBmy1pxmAim5FwDI_dY5iMeo2Pd3EfS35o03TYm-OFPlAB-kiM2Maam1GQZFlJLvb4xtUKz15fd6kUg7RkyeyThCyfqYUmasybsFTruHJUwhu2jQRx68gDkJatxUBzSoRewpWjw_4hv0NCQ51sw3gEBvjq32dtzsJDS1DinY__clbShirpLPuDUJnBr6rt0i4edmmNT1AvanOl3WohooGlduZNmzODymuKOGRbV_qgm0x5JIAcMTZkfkqbgnUr4OSIazSnbfqtfFct_9WI_OKQ9wBvFWR4sXhgT6BvBuspMsQU_wUcUb3v08qfNL9VbHPpeT6oYrqkXkH1jPanDk5Vly403TUBBGAobwObNYjcbDYDBT-EWTw03qGNBtNZxcDKHorvmKLMNmjCKiaEP69s7LGhcasHBjTDlWtt51Uq1CI5lubWiSE_Li8qFQu-MuBbNzMGzaDSGiFEJKmL6R1SL5fyKcIVP9tQ34-bCwUQE

The **actual** destination is delimited by `https://l.facebook.com/l.php?u=` at the beginning and `%3F` at the end.

I've noticed that Skp Redirect doesn't seem to do anything on these types of links.  Is there any way to configure the extension so it works in this scenario?

Thanks for the help, love the app otherwise!

**Comment by sblask** [comment]
Not quite sure why as it's not in the default list, but I had facebook.com in my list of exceptions. Once I removed it the redirect was skipped as expected.

**Comment by leifalbor** [comment]
Just checked - facebook.com isn't shown in either my blacklist or whitelist.  Any other ideas?

**Comment by sblask** [comment]
Where do you click the link? I just clicked one in my timeline and the redirect got skipped as expected.

You could also try to clear the blacklist or add `https://l.facebook.com/*` to your whitelist.

**Comment by leifalbor** [comment]
In my timeline - for example, the below anywhere on the below screen grabbed post

![image](https://user-images.githubusercontent.com/29937194/88639959-b8de4100-d100-11ea-866b-74fb5e6a3d25.png)

I've cleared the blacklist - no change
I've added `https://l.facebook.com/*` to the whitelist - no change 🙁

**Comment by sblask** [comment]
Not sure what to tell you, it just works for me. Are you sure the link you click actually contains the target URL like the link you posted above? Google for example changed search result URLs when clicking them in the past, maybe Facebook does something similar for you?

**Comment by leifalbor** [comment]
> Are you sure the link you click actually contains the target URL like the link you posted above?

...Fairly sure...? 🤷🏻‍♂️

> Google for example changed search result URLs when clicking them in the past, maybe Facebook does something similar for you?

Yeah, anything is possible!

Either way, if the extension is working fine for everyone else for Facebook links - I can only assume it's something local at my end that's causing it.  Thanks for your help!
