### ISSUE TITLE
Following a twitter link loops you back to the website with the embedded tweet

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sblask/webextension-skip-redirect#172]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)
If you click on the embedded tweet here:
https://www.zerohedge.com/health/sturgis-motorcycle-rally-kicks-bang-amid-virus-controversy-84-arrests-226-citations-18
Skip Redirect loops you back to Zerohedge instead of sending you to Twitter.

This happens on any website with embedded tweets.

**Comment by sblask** [comment]
Add `ref_url` to your no-skip-parameters-list.
