### ISSUE TITLE
v2.3.0 now has a "toggle delay"

### ISSUE THREAD

**Issue by ImSpecial** [sblask/webextension-skip-redirect#174]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Since yesterday's version bump of this addon, there's now a long delay for when toggling Modes, eg. On/Off, at first it wasn't even even switching to "Off" for me when I would do the toggle, but then I realized you now need to wait 2-3 seconds for the switch to happen before closing the popup window for it to take effect.

Is this a bug or was this delay put in intentionally?

**Comment by sblask** [comment]
The delay was added intentionally, but obviously not well thought through. It was not supposed to delay radio or check box changes.
