### ISSUE TITLE
Can  hover:🔔  will always keep:🔔 ?

### ISSUE THREAD

**Issue by dnknn** [sblask/webextension-skip-redirect#183]
>  Win¹⁰ │ Chrome*  

![209_12203214](https://user-images.githubusercontent.com/10995302/92995534-0f7bcf00-f537-11ea-83df-e405da462f79.png)An interactive feature request improvement: 

- ## ❥ Expected behavior: 
　　　　🖱Mouse-hover:🔔  will always keep:🔔 (i.e: Will not disappear automatically)
>  　　　　use for ⚔ comparison  etc.....

- ## ❓ How to achieve: 
I don’t understand the code, but I know  API🔌
https://developer.chrome.com/extensions/notifications
And I have also seen such a function.

**Comment by sblask** [comment]
There is no API for `mouse over`

**Comment by dnknn** [comment]
@sblask Hi!

You try this extension , it can do.

Redirector 
https://chrome.google.com/webstore/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd
