### ISSUE TITLE
YouTube External Link Redirects

### ISSUE THREAD

**Issue by scribbler957** [sblask/webextension-skip-redirect#185]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [X] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [X] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

YouTube redirects external links in video descriptions (the ellipses take the place of tracking tokens and the url):
`https://www.youtube.com/redirect?redir_token=...=https%3A%2F%2F...&event=video_description&...`

As you can see, they're a simple pattern.
Thank you.

[Edited to remove the partial URL (got me a temp ban at pastebin) and deactivate the hyperlink.]

**Comment by sblask** [comment]
What's the problem, it just works?

**Comment by scribbler957** [comment]
Is it skipping the redirect behind the scenes?

**Comment by sblask** [comment]
The whole point of this extension is that you don't see the page in the middle. You can configure notifications and you see `skip` in the toolbar icon for a few seconds. There is nothing more to see.

**Comment by scribbler957** [comment]
My mistake. I was using it to avoid being sent places I didn't ask. I thought maybe I could use it to avoid G**gle's stalking.
