### ISSUE TITLE
conflict with Multi Account Containers

### ISSUE THREAD

**Issue by Wojtus11** [sblask/webextension-skip-redirect#188]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

This add-on conflicts with "Multi-account containers" with "Limit to designated sites" set. For example, I have a Facebook container. When opening a l.facebook.com/l.php... link, MAC reopens the tab in a "no container" and it results in endless loop.

**Comment by crssi** [comment]
I had a lot of problems with MAC and I ditched it a long long ago... replaced by [Containerise](https://addons.mozilla.org/firefox/addon/containerise/).

Do you have the same problems with Containerise?

Cheers
