### ISSUE TITLE
automate adding skipped redirects to no-skip list

### ISSUE THREAD

**Issue by atomGit** [sblask/webextension-skip-redirect#191]
the 'copy last skipped url' is problematic in that it often doesn't write the url to the clipboard, or must be clicked multiple before it does

whether this feature works or not isn't really my point however - i would like to propose a change that i think would eliminate this problem and make adding urls to the no-skip list easier

instead of having to copy and edit the last skipped url, then open the preferences and add it to the list, i would suggest changing the 'copy last skipped url' menu item to something like 'whitelist last skipped url' - upon clicking that, a pop-up is displayed with the url in an edit control so the user can edit it if need be, after which an 'enter' key press, or a 'save' button press would add the url to the list

**Comment by sblask** [comment]
I have no interest or time to work on this.
