### ISSUE TITLE
Feature req: add ability to redirect "Copy Link Location" 

### ISSUE THREAD

**Issue by BlaineEXE** [sblask/webextension-skip-redirect#196]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Is it possible to add the ability to redirect for links copied via <right click> -> "Copy Link Location" dialog? I like this functionality of "Remove Redirect," which is based on this project but seems abandoned as of 2/3 years ago.

**Comment by sblask** [comment]
I have no interest or time to work on this.
