### ISSUE TITLE
goto.walmart.com not skipped

### ISSUE THREAD

**Issue by yegle** [sblask/webextension-skip-redirect#200]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

I was expect the URL to be skipped because the "u=" in query string contains the actual URL. It did not work as expected:

https://play.golang.org/p/wrWhCX_SFsV

**Comment by yegle** [comment]
Hmm weird. I added the example to the unit test and it looks like the test does pass.

```
diff --git a/test-url.js b/test-url.js
index 9d23783..0966109 100644
--- a/test-url.js
+++ b/test-url.js
@@ -21,6 +21,7 @@ test("URL in query path - http URLs url-encoded and not", function(assert) {
     assert.equal(url.getRedirectTarget("http://"  + "www.some.website.com" + "/"  + "http%3A%2F%2F" +       someTargetUrlEncoded + "&unwanted", urlExceptions, parameterExceptions),        "http://"  + someTargetUrl);
     assert.equal(url.getRedirectTarget("http://"  + "www.some.website.com" + "/"  + "http%253A%252F%252F" + someTargetUrlDoubleEncoded, urlExceptions, parameterExceptions),                "http://"  + someTargetUrl);
     assert.equal(url.getRedirectTarget("http://"  + "www.some.website.com" + "/"  + "http%253A%252F%252F" + someTargetUrlDoubleEncoded + "&unwanted", urlExceptions, parameterExceptions),  "http://"  + someTargetUrl);
+    assert.equal(url.getRedirectTarget("https://goto.walmart.com/c/10451/567111/9383?subid1=fcbc08ac328b11eb9af9e6a63278c9240INT&veh=aff&sourceid=imp_000011112222333344&u=https%3A%2F%2Fwww.walmart.com%2Fip%2FProForm-XR-10-9-Power-Tower-with-Push-Up-Pull-Up-Dip-Stations-to-Build-Strength-at-Home%2F581758747", urlExceptions, parameterExceptions), "https://www.walmart.com/ip/ProForm-XR-10-9-Power-Tower-with-Push-Up-Pull-Up-Dip-Stations-to-Build-Strength-at-Home/581758747")
     assert.end();
 });
```

**Comment by sblask** [comment]
You'll need to tick `Skip redirects for URLs with the same public domain` if you want to skip here.
