### ISSUE TITLE
Feature Request: keep a list of domains with redirect requests skipped

### ISSUE THREAD

**Issue by yegle** [sblask/webextension-skip-redirect#201]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

The websites that serves the redirects are often beacons to collect user interests etc. (https://en.wikipedia.org/wiki/Web_beacon).

It would be awesome if SkipRedirect can keep a list of domains who are redirecting requests, and so that I can block these domains on PiHole/Adguard Home.

**Comment by sblask** [comment]
This isn't my use case and I don't have time/interest to work on it, but if you want to, go ahead. However, if you'd block these domains, none of the links using them will work. I don't think this is what you want. Skip Redirect you can at at least disable if something doesn't work.

**Comment by yegle** [comment]
It actually works fine with PiHole/Adguard Home (the blocked domains will resolve to 0.0.0.0).

I unfortunately don't have the Javascript skills to do it though.

**Comment by sblask** [comment]
If you click on a link `beacon.com?redirectto=target.com` Skip Redirect will skip to target.com. No need to block beacon.com. If instead of using Skip Redirect you block beacon.com you will get an error.

**Comment by yegle** [comment]
Right yes. What I mean is, I want to force every client in my home network to use SkipRedirect.
