### ISSUE TITLE
Google ad services link

### ISSUE THREAD

**Issue by jporkka** [sblask/webextension-skip-redirect#204]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates
- [ x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)

On google.com search for a product, such as "mtape usb label printer"
A top line of ads shows up (A "g-scrolling-carousel")
If you hover over the links it shows the final URL in the status bar, but the URL of the link doesn't include this destination.
Clicking on the links just lands you on the google home page (with skip-redirect enabled).

Similar results for other types of "ad" links from search results.

**Comment by sblask** [comment]
This is a site specific problem, you can add it to no-skip-urls-list if it causes you problems.
