### ISSUE TITLE
t.co not on the skip list???

### ISSUE THREAD

**Issue by privacyguy123** [sblask/webextension-skip-redirect#205]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Title says it all - we can't circumvent this Twitter analytics tracker somehow?

**Comment by sblask** [comment]
I have no idea of how t.co URLs look like. If nothing is skipped, there is probably no redirect URL anywhere.
