### ISSUE TITLE
Add lolinez.com

### ISSUE THREAD

**Issue by fabianski7** [sblask/webextension-skip-redirect#210]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

This is the URL with the destination site`
http://www.lolinez.com/?https://github.com`

**Comment by crssi** [comment]
Why would anyone do something like that? lol
