### ISSUE TITLE
Skip Redirect: archive.org missing?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [sblask/webextension-skip-redirect#214]
Opera,Chrome Addon Version 2.3.4 from github, Win 10.
http://web.archive.org/ seems to be not checked yet.

I saved: 
https://github.com/sblask/webextension-skip-redirect/
at: 
https://web.archive.org/save/
but the processed snapshot link: 
https://web.archive.org/web/20210127160006/https://github.com/sblask/webextension-skip-redirect/
leads not to the archive.org snapshot, instead back to github.
Only my problem with perhaps too much disturbing addons?
thx

**Comment by sblask** [comment]
You'll have to add it to you no skip url list. I don't add site specific things to the default list.

**Comment by Clemens-Ratte-Polle** [comment]
Skip-Urls-List
*://*.archive.org/*

OK, and running good :)
thx
