### ISSUE TITLE
Can you make it go the other way round too?

### ISSUE THREAD

**Issue by Spamlet** [sblask/webextension-skip-redirect#222]
Sorry if this is a daft question, as I am not a coder, and even find it hard to find any downloads when I am referred to this site to get them.
To my mind, this app, on the face of it, does the opposite of what it says: at least, relative to the situation I was in:
I was trying to read an old MS advice page about a Windows7 problem, but MS just tells us to 'upgrade' now, instead of letting us read all the accumulated wisdom from contributors to its user forums.
I thought I might still be able to catch the articles on the 'Wayback Machine' archive...
It turned out that there were several copies of the web page I wanted to read in the archive, but, when I clicked to open them, the only very briefly flickered the article title on the screen, before diverting to the new MS 'advice' site.

So, I was expecting this app to make the browser stick on the Wayback page, and not be diverted to the dead end of MS.
I can't recall ever wanting to be sped quicker to the diversion site, rather than stop at the one the link appeared to go to. :/

I do not follow the jargon very well, so it may be possible that the app can do what I was expecting, but, if so, it could do with an interface that the ordinary browser user can easily understand.  For example: for me, a simple 3 option dropdown on the toolbar would be best: 'on/off', 'stop in the middle', 'skip to the end'.  Then we could quickly change it from site to site as we experienced the problems.  I don't see how making lists in advance is of much use to me.

I like the way you're thinking though!

**Comment by OscarL** [comment]
@Spamlet. Maybe you should try something like: https://addons.mozilla.org/en-US/firefox/addon/stop-auto-reload/, which attempts to stop pages from "reloading", either to show new content (think "refresh"), or to send you to another page ("redirect").

On Firefox there is also a setting in "about:config" that reads "accessibility.blockautorefresh", setting that to false might help in your case (but might break sites that expect to be able to refresh).

This addon (Skip Redirect) works by "cleaning" the links you might click on a page (avoiding extra garbage/tracking).

Just my 2 cents, as a user of this particular addon, Take care.

**Comment by sblask** [comment]
I think you just have to disable Skip Redirect for the waybackmachine. Click on the icon, there is off which you refer to as `stop in the middle` and two options for on.
