### ISSUE TITLE
Redirect to "twitter.com"

### ISSUE THREAD

**Issue by kurikokata** [sblask/webextension-skip-redirect#225]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Hello.
My environment is firefox 87.0 and Skip Redirect 2.3.5.
Is there a setting to redirect to twitter.com at the following url?

Before redirecting:
https://twitter.com/UserName?ref_src=twsrc^tfw|twcamp^tweetembed|twterm^1234567890123456789|twgr^|twcon^s1_&ref_url=https://example.com/news/20210406-headline-news/
https://twitter.com/UserName/status/1234567890123456789/photo/1?ref_src=twsrc^tfw|twcamp^tweetembed|twterm^1234567890123456789|twgr^|twcon^s1_&ref_url=https://example.com/news/20210406-headline-news/
https://twitter.com/UserName/status/1234567890123456789?ref_src=twsrc^tfw|twcamp^tweetembed|twterm^1234567890123456789|twgr^|twcon^s1_&ref_url=https://example.com/news/20210406-headline-news/

After redirecting:
https://twitter.com/UserName
https://twitter.com/UserName/status/1234567890123456789/photo/1
https://twitter.com/UserName/status/1234567890123456789

**Comment by sblask** [comment]
No, but I am sure there are other extensions that can do that.
