### ISSUE TITLE
[BUG]: Can not bypass queue-it.net

### ISSUE THREAD

**Issue by Drjacky** [sblask/webextension-skip-redirect#228]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [X] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [X] Chrome

### What is your operating system?

- [ ] Linux
- [X] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
Website: https://www.Republic.co

Tested version: 2.3.5

**Comment by sblask** [comment]
I can't really tell what is supposed to not work here. You didn't provide a URL that contains another URL.

**Comment by Drjacky** [comment]
https://republic.queue-it.net/?c=republic&e=6&ver=v3-javascript-3.6.3&cver=13&man=Default%20redirect%20all&l=Republic%20Theme&t=https%3A%2F%2Frepublic.co%2F&kupver=cloudflare-1.2.0

But for now, seems Republic.co has been disabled the queue and without waiting in line, we can visit their website.

**Comment by sblask** [comment]
When I go to https://republic.queue-it.net/?c=republic&e=6&ver=v3-javascript-3.6.3&cver=13&man=Default%20redirect%20all&l=Republic%20Theme&t=https%3A%2F%2Frepublic.co%2F&kupver=cloudflare-1.2.0 SkipRedirect skips to https://republic.co/ so it's doing exactly what it's supposed to do.

**Comment by Drjacky** [comment]
Even without having your extension installed, it redirects directly to the website now.
As I said, seems they disabled the queue for now.

I'll let you know when they activated it so, you can check it with the installed extension.
