### ISSUE TITLE
How to add exception for a bookmarklet

### ISSUE THREAD

**Issue by blogdemoi** [sblask/webextension-skip-redirect#237]
Hello,

How can I add an exception for a bookmarklet that redirects to Wayback Machine?

I navigate to a site, I wish to save it in Wayback Machine https://archive.org/web/ .
To do this I have a javascript bookmarklet ( javascript:void(window.open('https://web.archive.org/save/'+location.href)); )  in my Firefox https://en.wikipedia.org/wiki/Help:Using_the_Wayback_Machine#JavaScript_bookmarklet .

How can I add an exception for this with settings in Skip Redirect being: 
Skip all redirects except for URLs matching any of the lines in the no-skip-urls-list

Thank you.

**Comment by sblask** [comment]
Just add `archive.org`?
