### ISSUE TITLE
Anti-Tracking missing in infos

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [sblask/webextension-skip-redirect#240]
hi
The info that Skip Redirect also protects from tracking is missing not only here:
https://github.com/sblask/webextension-skip-redirect/tree/6cf0c2b4a333897fc2692b134a89bfda74f08a2f
:)

**Comment by sblask** [comment]
This is not what this extension is for. Great if it works for you, but it's nothing I support in this extension.
