### ISSUE TITLE
Facebook tracking appendix

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [sblask/webextension-skip-redirect#241]
Hi.
How to antitrack FB appendix? :
url.com/?fbclid=...
Is No-Skip-Parameter "fbclid" ok?
thx

**Comment by sblask** [comment]
Not sure what you are after, if you want to remove tracking parameters, there are better extensions for that.

**Comment by Clemens-Ratte-Polle** [comment]
> Not sure what you are after, if you want to remove tracking parameters, there are better extensions for that.

ok, thanks. Which extensions do you know for that?

**Comment by crssi** [comment]
[ClearURLs](https://addons.mozilla.org/firefox/addon/clearurls/)
[Neat URL](https://addons.mozilla.org/firefox/addon/neat-url/)
