### ISSUE TITLE
Skip redirect on web tmol

### ISSUE THREAD

**Issue by Zorroblanco** [sblask/webextension-skip-redirect#243]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Hi, I have a problem whit this web https://lectortmo.com/    mangas with adult content (nsfw) redirect to other site for example https://lectortmo.com/library/manhwa/55289/the-woman-who-lives-in-my-room  if you click cap 1 redirtec to https://fanaticmanga.com/news/122c7d14f4dee1e3613f112891fa66b3/cascade , the correct should be https://lectortmo.com/viewer/122c7d14f4dee1e3613f112891fa66b3/cascade  (skip https://lectortmo.com/viewer/xxxx and go direct to https://fanaticmanga.com/news/xxxx)  how can I fix it?
Sorry for my english I hope you understand.

Cheers

**Comment by sblask** [comment]
Not exactly sure what you mean, but there is no magic, if there is no URL encoded in the URL, SkipRedirect can't do its thing.
