### ISSUE TITLE
Skip redirect on web dramaday.net

### ISSUE THREAD

**Issue by monyau** [sblask/webextension-skip-redirect#247]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [ x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [x ] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
dear sblask,

thank you very much for your webextension-skip-redirect,
but it doesn't work in: 
https://dramaday.net/light-on-me/
https://dramaday.net/so-not-worth-it/
https://dramaday.net/my-husband-oh-jak-doo/
https://dramaday.net/my-lovely-girl/
https://dramaday.net/moorim-school/
https://apk.miuiku.com/post/tiktok-business
https://dramaday.net/my-lawyer-mr-jo/

can your please kindly update the script?
thank you very much indeed!

**Comment by sblask** [comment]
What do you expect to happen? When I click on one of your links, I go straight to the page.

**Comment by monyau** [comment]
i go to:
https://dramaday.net/light-on-me/
click Episode 01->1080p WEB-DL->Google Drive
it link to: https://apk.miuiku.com/post/top-popular-ryptocurrencies
not link to a google drive link

**Comment by sblask** [comment]
There is no URL embedded in that URL, so nothing can be skipped to.

**Comment by monyau** [comment]
https://dramaday.net/light-on-me/
1) if i turn webextension-skip-redirect **on**
i click Episode 01 -> Google Drive
it links to https://apk.miuiku.com/post/top-popular-ryptocurrencies

2) if i turn webextension-skip-redirect **off**
i click Episode 01 -> Google Drive
it goes to   https://apk.miuiku.com/post/best-samsung-themes
i click "clich hier to continue" -> wait 10 seconds -> click "get link" ->
and than i get finally the link for google drive, i shall want this link: 
https://dddrive.me/jKkJy9u

**Comment by monyau** [comment]
ok, i understood.
however, thank you for your help!
i wish you a good day!
