### ISSUE TITLE
Skip redirect on skimfeed.com

### ISSUE THREAD

**Issue by m-p-3** [sblask/webextension-skip-redirect#251]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
The [Skimfeed](https://skimfeed.com/) links aggregator currently uses a redirect to track clicks, it would be nice if the redirect could be stripped off.

For example https://skimfeed.com/r.php?q=2tech&l=11837978&u=https://lifehacker.com/how-to-limit-spotify-from-tracking-you-because-it-know-1847496516 should simply be https://lifehacker.com/how-to-limit-spotify-from-tracking-you-because-it-know-1847496516

Thanks!

**Comment by crssi** [comment]
Strange, but it works here just as you would like to.

**Comment by sblask** [comment]
Yes, it just works. You might have switched Skip Redirect off or enabled `Skip redirects only for URLs matching any of the lines in the skip-urls-list.` or have something funny in your `No-skip-urls-list`.
