### ISSUE TITLE
intercelestial.com

### ISSUE THREAD

**Issue by 3xploiton3** [sblask/webextension-skip-redirect#252]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

https://pahe.ph/snake-eyes-g-i-joe-origins/

example:
https://intercelestial.com/red-planet/#
![image](https://user-images.githubusercontent.com/19517680/129830978-302dd06c-1b8a-45b5-89a4-3035899ef6c9.png)

**Comment by sblask** [comment]
I have no idea what you are trying to do and what is not working.
