### ISSUE TITLE
Interference with Bypass Paywalls Clean

### ISSUE THREAD

**Issue by yokoffing** [sblask/webextension-skip-redirect#253]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ x] I can reproduce the problem on the latest stable version (not nightly!)
- [ x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)

When visiting `https://qz.com/2012965/the-us-labor-shortage-is-just-a-wage-shortage/`, [Bypass Paywalls Clean](https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean) wants to redirect to `https://archive.today/newest/https://qz.com/2012965/the-us-labor-shortage-is-just-a-wage-shortage/`.

Skip URLs is reverting this link away from landing at `https://archive.ph/20210624184211/https://qz.com/2012965/the-us-labor-shortage-is-just-a-wage-shortage/`.

How can I whitelist this behavior?

**Comment by crssi** [comment]
Add:
```
//archive.today/
//archive.ph/
```

to the `No-skip-urls-list` section.

Cheers

**Comment by yokoffing** [comment]
Thanks! This worked for me!

**Comment by mirror176** [comment]
A more complete list would be:
//archive.today/
//archive.fo/
//archive.li/
//archive.md/
//archive.ph/
//archive.vn/

**Comment by eylenburg** [comment]
I think this should be whitelisted by default. I think anyone who goes to the archive site does so on purpose.
