### ISSUE TITLE
Rule for archive.org not working

### ISSUE THREAD

**Issue by eleius** [sblask/webextension-skip-redirect#254]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

I added the rule `*://*.archive.org/*` (from one of the closed issues) to the skip-urls-list (it's my only custom rule), but it doesn't seem to work. When I click one of my bookmarked web.archive.org links for "archived" websites, Firefox still tries to reach the original server instead of the archive.org backup.

Note: I have addons like clearurls installed, and the arkenfox user.js, don't know if they can interfere with this addon.

**Comment by eleius** [comment]
I was mistakenly using the skip-urls-list, so I moved the rule to no-skip-urls-list (for some reason the starting asterisk causes "nothing to repeat" so I had to write it as `https://*.archive.org/*` instead). Still the problem persists...

**Comment by crssi** [comment]
`//web.archive.org/`

**Comment by eleius** [comment]
Thanks, it works

**Comment by crssi** [comment]
See mine other exclusions in my profile. It might suit you. 
Cheers
