### ISSUE TITLE
Urls not starting with www doesn't get skipped to.

### ISSUE THREAD

**Issue by itsfarseen** [sblask/webextension-skip-redirect#255]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Magnet urls don't get detected.

Example:
```
https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3A864AF2C28C24E1D0A598A03D83F15C6A7E6191D7%26dn%3DHow%2Bto%2BTrain%2BYour%2BDragon%2B%25282010%2529%2B1080p%2BBrRip%2Bx264%2B-%2B1.4GB%2B-%2BYIFY%26tr%3Dhttp%253A%252F%252Finferno.demonoid.me%253A3414%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.yify-torrents.com%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.1337x.org%253A80%252Fannounce%26tr%3Dhttp%253A%252F%252Fexodus.desync.com%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.openbittorrent.com%253A80%252Fannounce%26tr%3Dhttp%253A%252F%252Fretracker.hotplug.ru%253A2710%252Fannounce%26tr%3Dhttp%253A%252F%252Ftracker.yify-torrents.com%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.zer0day.to%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fcoppersurfer.tk%253A6969%252Fannounce
```

This also doesn't get detected:
https://mylink.cx/?url=google.com

This works:
https://mylink.cx/?url=www.google.com

This doesn't work:
https://mylink.cx/?url=images.google.com

**Comment by sblask** [comment]
I am not saying it's impossible, but it would make the logic quite a bit more complex whereas just checking for `www` is really simple AND I don't have time to look into it. I think supporting magnet URLs would be simpler. Maybe you want to look into it?

**Comment by itsfarseen** [comment]
I'll look into it. What do you think about maintaining a list of known redirect urls? like mylink.cx/?url= and google.com/?url=

**Comment by sblask** [comment]
Cool. I try to keep this as generic as possible and don't want site specific things in the default skip/no-skip lists either, otherwise I will be busy maintaining only that.

**Comment by atomGit** [comment]
seems i'm seeing the same problem

linux, firefox, skip redirect v2.3.6 (amo)

ref: `https://steamcommunity.com/sharedfiles/filedetails/?id=707020288`

link: [12bytes](https://steamcommunity.com/linkfilter/?url=http://12bytes.org/articles/gaming/cs-go-game-sound-optimization)[12bytes.org]

this should redirect to a 404 on 12bytes.org, however instead it leads to:
`https://steamcommunity.com/linkfilter/?url=http://12bytes.org/articles/gaming/cs-go-game-sound-optimization`

**Comment by crssi** [comment]
@atomGit It works fine here too.
