### ISSUE TITLE
Blacklist does not work on Amazon website

### ISSUE THREAD

**Issue by ulli5** [sblask/webextension-skip-redirect#256]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
I want to sort Amazon search results by price in ascending order. E.g. https://www.amazon.de/s?k=bluetooth+headset+in+ear&rh=p_72%3A419117031&s=price-asc-rank&dc
If Skip Redirect is turned off, this will work. When Skip Redirect is turned on, it does not work.
After I put "/www.amazon" in the blacklist, the sorting is still not done. Also "www.amazon" does not work.
If the sample seems to work, change the sorting and it will fail.

**Comment by sblask** [comment]
If anything, it's probably `amazon.de` you need to add, but for me sorting results doesn't work at all with Chrome, even without extensions.
