### ISSUE TITLE
White List

### ISSUE THREAD

**Issue by Threesom666** [sblask/webextension-skip-redirect#26]
Im not sure if Im using it right but Ive entered several different urls and it keeps blocking those sites. I need to white list stylish addon. When I click Find styles for this site feature. I cant see to get it whitelisted. Also Espn. Under Espn Games keeps getting blocked. Previously this didnt happen before the update. Though I like the update I dont know why it gets blocked. The site changes but I cant get it to white list. I entered the different codes like the examples and nothing seems to work. Im not sure if I should get it more time as there isnt a save button or Im not entering the codes right.

A whitelist button and a temporary whitelist while being redirected would be a good idea. 

Also since its sort of a adblock. An antivirus before we get to the site and/or database Blocked before we get there because of reports of virus or bad site.

**Comment by sblask** [comment]
I am not sure what your problem is. This add-on does not "block" anything. Please give me an example of what you expect on which site including URLs/links and what actually happens. If you are on Chrome, there was an issue where changing the mode and disabling the notification popup did not always work, but it's fixed now. So please try again.

**Comment by Threesom666** [comment]
It blocks the redirects. 
Im using firefox. The Addon Stylish has a feature where you click on it and to  find more styles for the page your on. Appearantly it searches for their site for the site im on but skip blocks them from redirecting it. Making it unusable. If I turn it off it works normal.


The other time it acts the same with is with games.espn.
I cant seem to remember but I know it has to do with games.espn.com 

I used this as example. http://games.espn.com/flb/clubhouse. If I take it redirect it goes to the site even though its an error. If I have your addon I get The page isnt redirecting properly message from firefox. Espn tries to use prior site to get to the future one. Its like it searches it to get to where its suppose to but redirect doesnt let it so it goes dead. Just like in stylish thats what happens. Ive notice that usually when it occurs it has to deal with a page popping up.

**Comment by sblask** [comment]
Now I see what you mean. You have two options here:
 - use blacklist mode and add `https://userstyles.org/` and `http://games.espn.com` to the blacklist, so no redirects are skipped for these sites. Skip Redirect will still try to skip redirects on sites that don't match anything in the blacklist.
 - use whitelist mode - no redirects are skipped by default, you have to add URL patterns to the whitelist manually to skip redirects on those sites

**Comment by Threesom666** [comment]
ok the first black list optioned work. But thats a bit confusing. I dont know why anyone would add the url to a blacklist thats supposed to be a whitelist. 

Two. The whitelist mode is very complicated. I tried to follow all of its instructions by adding all of its type of sites and nothing worked. It was also too much of a hassel. And very hard to understand. I think an example or an automatic code wouldve been better by entering the site and it giving the codes automatically.

Thirdly. I added a bunch of suggestions to upgrade the addon. Hope you take it into condsideration.

**Comment by sblask** [comment]
I think you find this confusing because you think of what this add-on is doing as blocking, but it isn't blocking, it's about skipping. Think of a spam filter, with a blacklist, any mail address that's on the blacklist will be blocked. With a whitelist, only mail addresses that are on the whitelist are accepted. With this add-on, all suitable redirects are skipped, apart from what's on the blacklist OR no redirects are skipped unless they are on the whitelist...

The whitelist mode is all about manually configuring what is known to work. It's the last resort if all things automatic failed. If you want simple, use blacklist mode and remove everything in the blacklist. If something is redirected the wrong way, switch Skip Redirect off, do your thing and when done go back to blacklist mode. (I imagine this is what you meant by whitelist button/temporary whitelist?) I think the link contains plenty of examples, but in any case, my whitelist currently looks like this:

```
http://redir.xing.com/link/*
https://slack-redir.net/link*
https://*.facebook.com/l.php*
https://deref-gmx.net/mail/client/*
https://outgoing.prod.mozaws.net/*
```

I didn't quite get what you meant by antivirus, but it sounds like you want to have an intermediary page before going to the final link? This would be exactly what this add-on is trying to get rid off...

**Comment by Threesom666** [comment]
This is a better response to your previouses. I gave you a summary in the firefox summary. I think this is one of better utilities out there but with a little more work it can be invincible! Okay, I get the skipping. By going over it which is almost as a good as not going at it at all as blocking is. Would be a great feature by the way. If we can add sites to it that it wont accept at all though they are all addons that do that that would just make this one better. 

I did think of it as spam filter. But when I addded it to whitelist nothing happened. I read the message on how to add it several times but no matter what I added in any variation it kept betting blocked( the firefox redirect/ or going back to my original site). It doesnt make sense to add it to the blacklist and I only did it because you told me to. It still doesnt make sense to me. Since if its blocked it should not go to it. Not accept it as it not being in the feature. There could also be a feature on this add as it goes through the links on the spot which to add to the white list and which to not. Without having to go to the addon. Example through the arrow pop up. Some links are good some not. We would know this as they come up while we to the page. Hence what I said adding a blocking feature not a skipping and whitelisting whats good. 

Turning on and off the clicker defeats the purpose of having the addon and having it work properly. When stylish changed its page( Like in april) to a newer version. I couldnt use the page and I went to stylish and complained. Now I think this was causing the issue all along but I never thought of it because in their previous version it didnt cause issues. Until it updated it's site and out of nowhere it couldnt direct its feature. I would just get an error. Now its all making sense. Through time for whatever reason it started to work again. Until you updated your addon and the the problem started again. Though I never put two and two together till now.

In the addon noscript. It blocks all the scripts from a page. Preventing us from being hacked, unnecessary ads, and looking at the stuff we want to see all the while making the page and computer run faster. If you go to a site and for whatever reason you want to watch some for a temporary time and then when you go back to the site it being blocked again it has a featured called temporary permissons. So what I mean by temporary is that you add a feature that we can temporary not redirect a site for a period of time and then we use the site after a temporary time( usually when we close the browser) the redirect would act as normal. Its a weird feature but very useful. Im glad they made it.


When I tried to whitelist those sites. I did plenty of those variations you did. But none worked. Maybe you can add it for me and send me the examples. It wasnt till i did the blacklist method. It would be a lot easier and better if we can just enter the url like i did in the blacklist in the white list.

When I mention antivirus/ intermediate page. I mean this!

The blacklist could be a lot A LOT! Larger. So that its like an antivirus. In this feature you would accept the user to submit pages to you to add to the blacklist. Giving us the user the power to submit a list and pages that you can automatically add and update to your addon that we can skip/block that wont appear and unnecessary waste our time and the addon would just skip/block from ever appearing on our browser because of ads, antivirus, unnecessary, and useless. While you the maker making sure it works properly. So in theory I did mean an intermediate but it as in a server before we get to the site but it doesnt necessary have to be like that as you said its designed to skip. So you can make a very good list to the black list so instead of going to the server we can just skip it all together. Hence like antivirus. Many adblocks do that. Antivirus. So instead of the user going one by one blocking it. A new comer can just add the addon and have the entire web contributing him a list he doesnt have to waste his time knowing. Or worst accidently getting a virus from.

**Comment by sblask** [comment]
If you look at the definition from Google:
```
In computing, a blacklist is a basic access control mechanism that allows everyone access, except for the members of the black list (i.e. list of denied accesses). The opposite is a whitelist, which means allow nobody, except members of the white list.
```
Then whitelist would be according to your line of thinking: `do not skip nothing unless on the whitelist` aka double negation and very hard to wrap one's head around.

I wouldn't know how to implement a temporary disable so it stays intuitive.

There is no way to react to clicks on the notification.

Maintaining a global whitelist or blacklist is nothing I am interested in, even if I'd get paid for it.

**Comment by Threesom666** [comment]
In any other program I use. the blacklist is the blocklist and the whitelist is the allowlist.

The Program that uses it is noscript. Maybe if you study it you could figure it out.

I understand there is no way to react to it. But so many other programs do react to notifications. That is my suggestion for your program.

Maybe your interest isnt the same as mine. As making this addon the best on the net. Many addons have such lists and adding one would enchance your addon making it stand it out more to the level of others implementing such practices. Only through improving it would you make it one of the best. 

Update: Ive noticed issues with skip Redirect. WHenever I have to send in info like user submitted information. It appears sites need to redirect for the info to go through and since it doesnt redirect it wont allow sites to work properly. I noticed it again when using espn games. And when loggin on to imdb.

**Comment by sblask** [comment]
I am repeating myself here, skip redirect does not block anything, it's about skipping redirects. noscript blocks scripts so it makes sense to put stuff that you want to block on the black list. With SkipRedirect, if you add stuff to the blacklist, skipping for it is blocked. If you put stuff on the whitelist, skipping is allowed.

See compatibility on https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/onButtonClicked no support for Firefox...

Feel free to start a wiki or other place to collect whitelist and/or blacklist entries. If it gains lots of traction, I might reconsider.

That's what the blacklist is for, just add the URLs that don't work.

**Comment by Threesom666** [comment]
You are repeating yourself, pointlessly. 

I didnt say it blocks. I simply suggested to add the blocking as an option in the add on.

I said you should study noscript for its temporary allow list. That way you can try to implement it on your add on as an improved enchanced optional version.

Any other program Ive used the whitelist allows it and the blacklist blocks it. This is the first time I see it the other way around. It didnt even occur to me till you mentioned it. And I still dont even like that idea. Because it allows it completely instead of allow specifically what I want and redirecting( blocking) what I dont. A suggestion I added above.

Noscript among other addons have the option when it has a popup notification to click on it for user options. To allow or block options among many others. 

I could start such a list, but first I have to know how to use the program properly. And then you should suggested it on addon so that I get fan support. I can start the list and they can add to it. In fact I have such a list already. Many lists. The problem would start who would go through it? I can start the list by personal list. Submitting my white and black lists. But who would go through it and green light the list it? My personal black and white list might not match the public. I also have many ad, malware, and antiviruses lists. I would love them to be submitted to the addon and automatically skipped. But what if my list causes issues with other users? It would need somebody to check the list and make sure it doesnt cause incompability issues. But first I have to get the hang of the addon which to this point has been a problem.
