### ISSUE TITLE
GQ.com link redirects

### ISSUE THREAD

**Issue by yokoffing** [sblask/webextension-skip-redirect#267]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

`https://www.gq.com/gallery/best-menswear-to-buy-on-amazon`

Clicking the product links redirects back to the `gq.com/gallery/best-menswear-to-buy-on-amazon`; it does not take you to the Amazon product page.

**Comment by sblask** [comment]
You'll need to add https://www.gq.com to your no-skip-url-list.

**Comment by yokoffing** [comment]
The links they use look like this: `https://cna.st/p/2hc5hQAHwgUB4mn72o2mkNsQCYcgfTutpWRcwFnjMtqbECuFBTt5nwpwko2YZWC6nfKDH8rvyUi3ywC6M9VD9dN7214HjEwuMUpgcZH5ogx?cid=58d9287454d2617a9a731149`

**Comment by sblask** [comment]
Then you need to add https://cna.st
