### ISSUE TITLE
/logoff is missing on Blacklist

### ISSUE THREAD

**Issue by crssi** [sblask/webextension-skip-redirect#27]
Hi
for sure `/logoff` is missing on Blacklist for completeness and maybe `/logon` too

cheers

**Comment by crssi** [comment]
another one:
`cred_submit`

**Comment by sblask** [comment]
`cred_submit`? where is that coming from?

**Comment by crssi** [comment]
Some ORACLE cloud login/sso crap ;)

**Comment by sblask** [comment]
I added logon and logoff, but not cred_submit. (to be released) The default list should be as generic possible and if people get problems with specific sites, they should add them manually. Otherwise I could spent my days maintaining the list...

**Comment by crssi** [comment]
Perfect
Thank you
