### ISSUE TITLE
Redirect Postmark

### ISSUE THREAD

**Issue by adriaanvanrossum** [sblask/webextension-skip-redirect#277]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

postmarkapp.com is using a shortener that has this format:

```
https://click.pstmrk.it/2sm/my.paddle.com%2Freceipt%2F00000000-00000000%2F00000000-aaaaa0aa000aa00-000aa00a0a/AaaAAAaA/0aA/aAAAaa0AA0/a0Aaa0AaaAA0aA0aA0AAA0AaaAA
```

It contains all data needed for a redirect, in this case, the page redirects to:

```
https://my.paddle.com/invoice/00000000-00000000/00000000-aaaaa0aa000aa00-000aa00a0a
```

I couldn't find in the source code if this is easy to implement, but something like this could work:

```js
const url = "https://click.pstmrk.it/2sm/my.paddle.com%2Freceipt%2F00000000-00000000%2F00000000-aaaaa0aa000aa00-000aa00a0a/AaaAAAaA/0aA/aAAAaa0AA0/a0Aaa0AaaAA0aA0aA0AAA0AaaAA" 
const matches = url.match(/https:\/\/click\.pstmrk\.it\/[a-z0-9]+\/([^/]+)/i);
const redirect = matches[1] ? "http://" + decodeURIComponent(matches[1]) : null;
```

**Comment by sblask** [comment]
These would be the places responsible for URLs that are part of the path:

https://github.com/sblask/webextension-skip-redirect/blob/main/url.js#L45
https://github.com/sblask/webextension-skip-redirect/blob/main/url.js#L25

As you can see only very general rules are supported, some protocols and `www`. No way to support your use case.

**Comment by adriaanvanrossum** [comment]
It's unfortunate it's not possible. But thanks for getting back to me. Appriciated.
