### ISSUE TITLE
ipinfo.io redirects dont get skipped

### ISSUE THREAD

**Issue by vxzilo** [sblask/webextension-skip-redirect#282]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)

I get a Newsletter from a Newspaper, when i click on the link in Thunderbird to be opened in Firefox it does not skip the redircet. The Redirect is to ipinfo.io and looks like this:
https://click.mc.tamedia.ch/?qs=2cbbe47badbe608e4c49e759460f70df3565e597cce572c821705ecc4f03c77ed0a5e854c7012676f5bd3bf64bd29b312ed66704e3dc71c7a7ee6287bafeffe6

**Comment by sblask** [comment]
Without the actual string I can't see whether there is a URL in there. Might just be a random string...

**Comment by vxzilo** [comment]
ah sorry. here is a full link:

https://click.mc.tamedia.ch/?qs=2cbbe47badbe608e4c49e759460f70df3565e597cce572c821705ecc4f03c77ed0a5e854c7012676f5bd3bf64bd29b312ed66704e3dc71c7a7ee6287bafeffe6

**Comment by sblask** [comment]
Yeah, just a random string, nothing I can do.

**Comment by vxzilo** [comment]
thanks for looking into it, appreciate it!
