### ISSUE TITLE
Interference from uBO

### ISSUE THREAD

**Issue by awebeer256** [sblask/webextension-skip-redirect#283]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

When clicking on a link that looks like `https://tracking-domain.com/?url=example.com`, with uBO installed and a filter like `||tracking-domain.com^` (AKA block everything from that domain), Skip Redirect will report a successful redirect to `example.com`, but the browser will navigate to the uBO page that says, *"uBlock Origin has prevented the following page from loading:…"* and stay there.

For example, ensure that "Peter Lowe’s Ad and tracking server list" is enabled in uBO, then go to `isthereanydeal.com`, and click the link to view a game on GreenManGaming.

This looks like a limitation in the way that the browser handles multiple extensions trying to modify the same network request.

**Comment by sblask** [comment]
Yeah, nothing that can be done there...
