### ISSUE TITLE
Doesn't seem to work for links in Gmail

### ISSUE THREAD

**Issue by e-t-l** [sblask/webextension-skip-redirect#287]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Gmail often rewrites hyperlinks in the body of emails as http://google.com?url=[actual_link.com]
I installed this extension and refreshed Gmail, but clicking a link in an email still calls google rather than directly calling the actual link. Is this extension broken on Gmail, or am I misunderstanding how this works?

**Comment by sblask** [comment]
Works for me: https://www.google.com/?url=www.example.com is skipping to example.com Google might do some Javascript magic though when you click on the link in Gmail.
