### ISSUE TITLE
Extension doesn't work with right click, Open Link in New Tab on Firefox

### ISSUE THREAD

**Issue by charonko-LANL** [sblask/webextension-skip-redirect#294]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

The extension seems to work fine when directly clicking a link, but if you right click and select "Open Link in New Tab" from the context menu, I still see redirect occurring (tested on a google.com search result page), and not being fixed by this extension.  Strangely, I think "Open Link in New Window" and "Open Link In New Private Window" may be working correctly - or at least the redirect is happening so fast I never see the intermediate page.

Using Firefox 91.5.0esr(64bit), Skip Redirect v2.3.5

**Comment by sblask** [comment]
I just tried and it works as expected.

**Comment by johnjc3** [comment]
Sorry, I tried again, and you are right.  I was confused by the brief appearance of the original URL in the address bar, but missed the popup that alerted me to the fixed redirect.  Sorry for wasting your time!

**Comment by charonko-LANL** [comment]
Sorry, I tried again, and you are right. I was confused by the brief appearance of the original URL in the address bar, but missed the popup that alerted me to the fixed redirect. Sorry for wasting your time!

**Comment by ZeroBomb** [comment]
Hey, just had this same issue with firefox on windows.

The problem occurs when you have two firefox _windows_ open, and try to "open in new tab" from the _second_ window.

**Comment by ZeroBomb** [comment]
Upon further trial and error and restarting, the problem seems a bit more random than this.

New observations:

- Open in new tab can fail on any window
- Once it fails, it will continue to fail (retrying is useless)
- If it succeeds once, subsequent attempts to open in new tab may still fail
- Possibly my adblock addon is in a race with the skip redirect addon?
  - If the adblock addon sees the redirectful link and goes to a block page, the skip redirect addon cannot skip to the true, non-blocked page?
