### ISSUE TITLE
Feature Request: Quick-add new entry to url-lists

### ISSUE THREAD

**Issue by e-t-l** [sblask/webextension-skip-redirect#295]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates (related to #23, but provides more context, and suggestions include adding this functionality to the toolbar button. Also, the "solution" to that issue is insufficient, as it's simply an opinion of, "I think it would be better if [users have to do something more complicated and time-consuming every time they encounter a false positive URL].")
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is ~not~ kinda about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description 

A feature that would vastly increase this extension's usability would be an option to quick-add a new entry into the active list (i.e. either no-skip-urls-list or skip-urls-list, depending on the active Mode). This could be implemented in any of several places, either upon clicking the toolbar icon, or perhaps by clicking the notification popup (if it's enabled). 

The feature would function something like this: 
1. A user attempts to navigate to a URL, and SR skips the redirect, but the user would like this URL _not_ to be skipped. 
2. When the user clicks on the popup notification, a new form appears, containing two buttons, "Add to List" and "Cancel," and a textbox that has been autofilled with the most recently skipped URL. 
3. The user can edit the textbox's contents to be only the desired string, then clicks, "Add to list." 
4. SR then does two things: 
    1. The string is added to the active list on a new line, 
    2. The tab navigates to the URL that SR had skipped (aka the URL that the user originally intended to visit).

**Comment by sblask** [comment]
I am not really interested in this. Why not just copy the last skipped URL (see toolbar icon context menu) and paste it in the right box in the options popup? I might work on #296 but "bringing up a text box" is not actually that simple and is functionality I don't want to add. I also don't have time for it.

**Comment by daveriedstra** [comment]
That's too bad, but I definitely get not having enough time. What you suggest works, it's just a lot of extra clicking around inserted into what should have been a simple page navigation, and there's only so many times someone will do that before uninstalling the extension.

**Comment by HyperCriSiS** [comment]
As this happens quite regularly this is really a needed feature. I do not want to copy paste URLs every time.
