### ISSUE TITLE
[Feature Request] Option to disable/hide "Add context menu entry to copy target URL" context menu item 

### ISSUE THREAD

**Issue by ImSpecial** [sblask/webextension-skip-redirect#299]
Title pretty much says it all. Update recently added this "feature" to the context menu, not everyone want's or needs this, it creates clutter in the context menu, can this be disabled in the options?

**Comment by sblask** [comment]
I just found out that this extension will probably stop working next year, so I am not going to put more effort into it, but you can open a PR.

**Comment by ImSpecial** [comment]
Incredible... I'm already looking for a replacement. :/

**Comment by crssi** [comment]
> I just found out that this extension will probably stop working next year, so I am not going to put more effort into it, but you can open a PR.

Why is that?

**Comment by sblask** [comment]
@crssi Because Manifest V2 will stop working and Manifest V3 does not have the API that I am currently using. You can thank Google for that. So whatever happens there is work that needs to be done, but without the API the only way to make this work is to intercept clicks on links. I am not sure I am up for that because it's a rabbit hole.

**Comment by ImSpecial** [comment]
Google/Chrome are the ones dropping the Manifest IIRC, Firefox is the one that are sticking with the other. Are you sure Firefox is affected here?

**Comment by sblask** [comment]
I am not using Firefox anymore and it's unclear what they will or will not do, the last update has been almost a year ago. SO there won't be much effort from my side, but PRs are welcome.

**Comment by dnmTX** [comment]
@sblask don't give up,just yet 😉  Chrome can be run with `--allow-legacy-extension-manifests` switch which will extend the life of essential extensions like yours.
Feature development is encouraged 👍

**Comment by shrublet** [comment]
Any chance this can be re-opened? Or is there still no interest. Apologies for the necropost.
