### ISSUE TITLE
Plain `/openid` is not enough

### ISSUE THREAD

**Issue by jvillasante** [sblask/webextension-skip-redirect#303]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ X] Firefox
- [ ] Chrome

### What is your operating system?

- [ X] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
Only having `\openid` is not enough anymore, for example, this is how Amazon redirects you these days (Amazon 'Your Account' -> 'Login and Security'):
`https://www.amazon.com/ap/cnep?openid.return_to=...&openid.identity=...&openid.assoc_handle=...&openid.mode=...&openid.ns.pape=...&openid.claimed_id=...&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0`

I had to add `openid.*` to my `No-skip-urls-list` and maybe that should be the default?

**Comment by sblask** [comment]
The default lists are only a best effort and aren't meant to cover everything I don't think I will make a change for openid...

**Comment by crssi** [comment]
@jvillasante 
Here are additions that I have build over the years using SR: https://github.com/crssi/Firefox/blob/master/Skip_Redirect-Blacklist.txt
There is also your exception listed.

Cheers

**Comment by crssi** [comment]
Oh... and sincerely thank you @sblask for one of the best extensions ever. ❤️
