### ISSUE TITLE
option to turn off the beep

### ISSUE THREAD

**Issue by pstephensonkiwi** [sblask/webextension-skip-redirect#306]
### New Issue Checklist (tick off like this: `[x]`)

- [ x] I checked existing issues (open and closed) for possible duplicates
- [ x] I can reproduce the problem on the latest stable version (not nightly!)
- [x ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

I love the extension but the beep drives me mad.  Make an option to turn it off?

**Comment by sblask** [comment]
Beep? What beep?

**Comment by pstephensonkiwi** [comment]
With the redirect notification comes an audible beep.  Do I have to just turn sounds off for all firefox notifications?

**Comment by sblask** [comment]
I guess, I am not aware of anything in the API.

**Comment by sblask** [comment]
I mean you can just disable the notification from SkipRedirect...

**Comment by pstephensonkiwi** [comment]
yeah, I guess a notification will beep if I've asked for firefox notifications to beep.
