### ISSUE TITLE
Infinite loop in gmail

### ISSUE THREAD

**Issue by georgedorn** [sblask/webextension-skip-redirect#31]
My primary interest in this extension is to fix GMail's broken tracking referrer.  But when I try to open a link, this extension flickers the redirection notification many times per second until I kill the tab and never actually goes to the non-referrer URL.

**Comment by sblask** [comment]
Without an example URL I can't really do anything. But getting redirect loops means that Skip Redirect will probably not help you in this case. Google does weird stuff in their links...

**Comment by georgedorn** [comment]
Gmail uses some JS to rewrite the URL just at the point you click on it.  So the URL to this issue page ended up being:
https://www.google.com/url?hl=en&q=https://github.com/sblask/webextension-skip-redirect/issues/31%23issuecomment-319194806&source=gmail&ust=[snip]&usg=[snip]

This is in the 'data-saferedirecturl' attribute on the anchor.

**Comment by sblask** [comment]
Yes, that is also what I got, but I never got a loop. I still had to disable Skip Redirect for google.com/url because it only partly urlencodes the URL (a link to youtube in my case) in the query string which makes Skip Redirect strip some part of the URL.
