### ISSUE TITLE
 Notifications off by default

### ISSUE THREAD

**Issue by zsalerno001** [sblask/webextension-skip-redirect#313]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [ x ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [ x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)

I am a Net Admin for a school district, and I have been getting non-stop reports from users for the past 2 months about the increase of redirect notices from Google. I came across this extension, and it works perfectly! The only request I have is if it would be possible to have the notification pop-up setting default to disabled on initial install of the Chrome extension. I would like to install this extension for all of our staff via the Google Admin console, but I can already tell you they will be just as upset seeing a pop up notification with every skipped redirect, as they are now seeing Google’s redirect notice. And yes, it is easy enough to go to the settings for the extension and uncheck the box, but half of these people will not be able to do that on their own, and the other half will be pissed off that they are being asked to change the settings themselves. :) Thank you in advance!

**Comment by sblask** [comment]
This extension will probably stop working son on Chrome because Chrome will deprecate the API being used. Also having the notification on by default is by design because the extension doesn't work perfectly and if something doesn't work, users should be able to see why and disabling it should be a conscious decision.
