### ISSUE TITLE
Notifications are not shown

### ISSUE THREAD

**Issue by NilsHoyer** [sblask/webextension-skip-redirect#316]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

The notifications are not shown. Inside the DevTools of Chrome, I get this message: `Uncaught (in promise) Error: Failed to set icon 'icon-off.svg': The source image could not be decoded.`

**Comment by sblask** [comment]
Works for me.
