### ISSUE TITLE
*.wiki.fc2.com

### ISSUE THREAD

**Issue by austinhuang0131** [sblask/webextension-skip-redirect#323]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Format is `https://*.wiki.fc2.com/jump/<protocol>/<url-encoded path>`. It goes to an external link disclaimer page so it doesn't automatically redirect.

eg. https://practice.wiki.fc2.com/jump/http/help.fc2.com%2Fwiki%2Fmanual%2FHome%2Fmanual01%2Fedit.html => http://help.fc2.com/wiki/manual/Home/manual01/edit.html

**Comment by sblask** [comment]
This extension does not use path rules for specific URLs to find other URLs, it tries to match URLs in URLs in a more generic way. Just having `wiki.fc2.com` is not a good indicator for a URL.
