### ISSUE TITLE
nature.org - Access through your institution

### ISSUE THREAD

**Issue by davidkopp** [sblask/webextension-skip-redirect#324]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Login with "access through your institution" does not work.

The Link
https://wayf.springernature.com/?redirect_uri=https://www.nature.com/articles/s41545-021-00140-3
should not be redirected directly to https://www.nature.com/articles/s41545-021-00140-3

Possible solution:
Add `redirect_uri=https://www.nature.com/articles/*` to the default no-skip-urls-list

**Comment by sblask** [comment]
I don't add website specific entries to the default lists .
