### ISSUE TITLE
Same-domain redirect still being skipped on archive.is

### ISSUE THREAD

**Issue by sumyungguy** [sblask/webextension-skip-redirect#33]
With "Skip redirects for URLs with the same public domain" box unchecked, go to archive.is and enter a URL to search for a saved snapshot. The search button should lead to `archive.is/search/?q=url` but it's skipped and you go to the actual URL.

edit: It's also skipping on archive.org "wayback machine"

**Comment by sblask** [comment]
This works just as expected. The same public domain option would apply for `http://archive.is/search/?q=http://archive.is/something` If enabled, it would go to `...something` if disabled it doesn't. As in your example it's not the same domain, it skips in any case. Bear in mind that this extension "tries" to do the right thing, but there is no definitive automatic way to tell whether the page behind `http://archive.is/search/?q=http://archive.is/something` is a proper page or is just there to redirect. You'll have to add `archive.is` to your blacklist if you don't want skipping to happen.

**Comment by sumyungguy** [comment]
Very sorry, I don't know what I was thinking when I posted that. I guess I didn't get much sleep last night.
