### ISSUE TITLE
[Feature request] Website permissions

### ISSUE THREAD

**Issue by donnydark0** [sblask/webextension-skip-redirect#332]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [X] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [X] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Please consider adding support for more granular website permissions. In this case a blacklist would probably make more senese, i.e. blacklist sites the extension has no access to read and alter content.

**Comment by sblask** [comment]
There is no way to implement a blacklist. An extension can either have permission to all sites or has to ask for access to every single one it needs access to. This would be super annoying.
