### ISSUE TITLE
No redirect to the login page on www.olx.pl

### ISSUE THREAD

**Issue by wojnilowicz** [sblask/webextension-skip-redirect#336]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
Clicking on "Twoje konto" on https://www.olx.pl/ fails to redirect to the login page.
![image](https://user-images.githubusercontent.com/22069602/213882578-5f5d67ff-3e00-4b45-97e0-71cacfddcf9c.png)

**Comment by sblask** [comment]
You'll have to add www.olx.pl to your no skip list
