### ISSUE TITLE
sites supported

### ISSUE THREAD

**Issue by davidp88** [sblask/webextension-skip-redirect#338]
What's the total number of sites supported for this

**Comment by pe1uca** [comment]
I don't fully understand your question.  
For "Skip all" the "no skip" list is limited to the limits of the RegExp implementation of the browser   
https://github.com/sblask/webextension-skip-redirect/blob/95af55c55378440a7e31aa919fba41ede05ed55c/url.js#L129  

For the "Skip only" the list is limited to the limits of the [webRequest filter](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/RequestFilter)  
https://github.com/sblask/webextension-skip-redirect/blob/95af55c55378440a7e31aa919fba41ede05ed55c/background.js#L334-L338

**Comment by davidp88** [comment]
for how many sites does this extension work

**Comment by sblask** [comment]
This extension does not have a list of rules for a list of sites. So there is no number to give. It's an advanced tool for users who know what they want and can add exceptions if necessary.
