### ISSUE TITLE
white list not working? tineye.com

### ISSUE THREAD

**Issue by atomGit** [sblask/webextension-skip-redirect#34]
firefox v54
Skip Redirect v2.2.0

reference page:

`http://www.news.com.au/travel/travel-updates/incidents/old-us-naval-intelligence-photo-said-to-show-amelia-earhart-her-copilot-and-the-wreck-of-her-aircraft/news-story/c0d11fb1d75b1996033716145af63185`

i have [an extension installed](https://addons.mozilla.org/en-US/firefox/addon/image-search-options/?src=search) that allows reverse image searching - when i try to do a reverse image search for the first photo in the reference page on tineye.com, the redirect is always cleaned despite tineye.com being whitelisted

things i've tried in the whitelist include...

`http://www.tineye.com/*
*://*.tineye.com/*
http://www.tineye.com/search/?url=http%3A%2F%2Fcdn.newsapi.com.au%2Fimage%2Fv1%2F8794938b88e8f3427bf8c78df804b0d3`

**Comment by sblask** [comment]
You have to use the blacklist.

**Comment by POA7R** [comment]
The white list and the black list do seem to be reversed from what I would assume theoy do upon first hearing the name.
