### ISSUE TITLE
Skip all redirects mode causes login loop on Atlassian

### ISSUE THREAD

**Issue by wesinator** [sblask/webextension-skip-redirect#347]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

With `Skip all redirects` mode, the exclusions do not apply to Atlassian SSO login, and causes an infinite loop when logging into atlassian cloud with sso.

URL: `https://id.atlassian.com/login/authorize?application=jira&continue=https%3A%2F%2Fid.atlassian.com%2Fjoin%2Fuser-access%3Fresource%3Dari%253Acloud%253Ajira%253A%253Asite%252F` ...

I would think the `/login` exclusion would handle this URL but it didn't at the time of writing.

**Comment by sblask** [comment]
I am getting a BadRequest page for the link you posted, but even just https://id.atlassian.com/login/authorize?application=jira&continue=https%3A%2F%2Fid.atlassian.com should trigger redirect skipping if the `/login` were not working.

**Comment by wesinator** [comment]
> I am getting a BadRequest page for the link you posted, but even just https://id.atlassian.com/login/authorize?application=jira&continue=https%3A%2F%2Fid.atlassian.com should trigger redirect skipping if the `/login` were not working.

try visiting `https://acme.atlassian.net/browse/EXAMPLE-123` (notional JIRA link example)

the link was an incomplete reference link, I didn't want to private a full private link. 

You might reproduce attempting to visit jira from an id.atlassian.net /JIRA URL in your history, with an SSO login account.

**Comment by sblask** [comment]
The brings me to: https://id.atlassian.com/login?continue=https%3A%2F%2Fid.atlassian.com%2Fjoin%2Fuser-access%3Fresource%3Dari%253Acloud%253Ajira%253A%253Asite%252F84d20082-20e4-41d4-9582-0fcc32d93529%26continue%3Dhttps%253A%252F%252Facme.atlassian.net%252Fbrowse%252FEXAMPLE-123&application=jira and I don't get any looping. Maybe you have another extension enabled that causes this>

**Comment by pe1uca** [comment]
I added these to the skips and now it works properly.  
```
id.atlassian.com/login/authorize  
id.atlassian.com/join/user-access
```
