### ISSUE TITLE
don't seem to work with firefox 115 on windobz 11

### ISSUE THREAD

**Issue by iznobe** [sblask/webextension-skip-redirect#349]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)
doesn't skip redirect popup on firefox  115 .
match pattern used to test  : *://*.ubuntu-fr.org/*

**Comment by sblask** [comment]
I get an error: `Please use $(ref:runtime.getURL)` because `browser.extension.getURL` is deprecated. But that shouldn't be an error as long as `browser.extension.getURL` has not been removed. So I think that's a Firefox bug.
