### ISSUE TITLE
suggested small improvements...

### ISSUE THREAD

**Issue by atomGit** [sblask/webextension-skip-redirect#35]
* left click = disable/enable without having to open the preferences and select "off", then add a "preferences" item to the right-click context menu

* suggest opening the pattern instruction page in a new tab

* might want to keep a small log of the last 'x' number of redirects and display it in the preferences UI???

**Comment by sblask** [comment]
1: I had it like this at some point, but after adding another mode it's more obvious opening the preference popup. You'd probably need to click twice anyway to get what you want.
2: I actually thought that would happen already. I might make it so, until then you can always middle click or right click.
3: I though about it, but having the last redirect seemed enough. You can see it in the tooltip and also copy using right click on the icon.
