### ISSUE TITLE
skipRedirect icon persists in the address bar even after removing it

### ISSUE THREAD

**Issue by 100priyal** [sblask/webextension-skip-redirect#351]
After installing the extension, I got 2 skipRedirect icons(one without its logo as shown in the 1st and 3rd img).
If I remove the extension, the one of them stays in the address bar which is unusable and can't be right clicked, so can't be removed. After removing the extension, it doesn't show in the chrome://extensions/ page.

![2023-08-06 18_14_34-D__ _2023-08-06 18_12_03- png  _  17_20 file(s)  _  86 76%  _  461 x 355 px  _](https://github.com/sblask/webextension-skip-redirect/assets/23549914/9dc8207d-6333-458a-aaba-8eb069a1468f)

- Browser: vivaldi 6.1.3035.257(chromium based)
- OS: Windows11

**Comment by sblask** [comment]
That is most likely a Vivaldi bug, have never seen that before and nothing has changed in a long time.
