### ISSUE TITLE
Copy last skipped URL not working

### ISSUE THREAD

**Issue by acjay** [sblask/webextension-skip-redirect#352]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

When in "Skip all redirects except for URLs" mode, when the extension skips a redirect that I need, I try to use the "Copy last skipped URL" feature but my clipboard just has whatever it previously had when I past into the "No-skip-urls-list".

**Comment by sblask** [comment]
This looks like a Firefox bug to me, there is an error for missing host permissions, but host permissions are not part of the webextension version Skip Redirect is built with.
