### ISSUE TITLE
hb.afl.rakuten.co.jp redirect not skipped

### ISSUE THREAD

**Issue by contextnerror** [sblask/webextension-skip-redirect#353]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
The link `http://hb.afl.rakuten.co.jp/hgc/g00qteh4.3e8j1a7c.g00qteh4.3e8j24f3/?pc=http%3A%2F%2Fitem.rakuten.co.jp%2Fhellobungu%2F12502077%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fhellobungu%2Fi%2F10014725%2F` does not seem to trigger skip redirect. Since this url has multiple parameters I have tried to add `m` to no-skip-parameters as per the README. But this does not seem to do anything. Neither does adding `pc`. What am I missing?

**Comment by sblask** [comment]
You have to tick the `Skip redirects for URLs with the same public domain` box for that to work.
