### ISSUE TITLE
Link to .../www.html wrongly recognized as redirect

### ISSUE THREAD

**Issue by halms** [sblask/webextension-skip-redirect#354]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
The [ASGI Documentation](https://asgi.readthedocs.io) has one page:
https://asgi.readthedocs.io/en/latest/specs/www.html
Skip redirect recognizes this as a redirect to `http://www.html` which is obviously wrong.
Can of course be solved with the `no-skip-urls-list`, but maybe this is a hint that the redirection identifier is a bit too eager?

**Comment by sblask** [comment]
I wouldn't say it's obviously wrong. www.some_tld is a valid address. Fixing this would be a bit messy, so I'll leave it alone.
