### ISSUE TITLE
Clicking on pictures in Reddit results in redirect error in Firefox

### ISSUE THREAD

**Issue by SD777x** [sblask/webextension-skip-redirect#356]
### New Issue Checklist (tick off like this: `[x]`)

- [ X] I checked existing issues (open and closed) for possible duplicates
- [X ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [ X] Windows

### Description (please include examples/screenshots where applicable)

When clicking on a picture in a reddit post on www.reddit.com in Firefox the new tab with the enlarged picture gets the following error:

The page isn’t redirecting properly
An error occurred during a connection to preview.redd.it.
This problem can sometimes be caused by disabling or refusing to accept cookies.

This happens with any picture in a post, can recreate.  Turning off the extension fixes it.  I'm not sure how to add a url to the exception list or if that's possible.

**Comment by sblask** [comment]
Just add `reddit.com` to the no-skip-urls list.

**Comment by SD777x** [comment]
Awesome TY that worked!
