### ISSUE TITLE
Chrome Webstore version legit? Updates?

### ISSUE THREAD

**Issue by Sanzium** [sblask/webextension-skip-redirect#357]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [N/A] I can reproduce the problem on the latest stable version (not nightly!)
- [N/A] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [X] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [X] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [X] Android (Kiwi Browser)

### Description (please include examples/screenshots where applicable)
Hello.
I would just like to make sure if the version available at the Chrome Web Store is legit ( https://chrome.google.com/webstore/detail/skip-redirect/jaoafjdoijdconemdmodhbfpianehlon ), because I see no mention to it here in GitHub as there is a link to the Firefox Add-ons.
If it is legit, maybe you could put the link alongside Firefox's one (maybe I'm being too paranoid, but it's always good to be sure 😃).
Besides, are there plans for releasing updates in the short term? It's been a while since the latest stable version. What about a pre-release or nightly builds?
Thanks in advance!

**Comment by sblask** [comment]
Yeah, that's me. There can only be one link in the Github about. If you are paranoid you can checkout this repo and run from there?

Nope, no updates planned. If I have time I might tackle some small issues, but generally speaking this extension is complete. But it might stop working when manifest version 3 gets enforced.

So far builds are manual, but if you want to put some time in to automate stuff you are welcome!
