### ISSUE TITLE
Error downloading files on google drive

### ISSUE THREAD

**Issue by phuongnamhoangde** [sblask/webextension-skip-redirect#358]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- **[x]** If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- **[x]** Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- **[x]** Windows

### Description (please include examples/screenshots where applicable)

I can't download files on google drive, even though I added them to the exclusion list. Please assist me with the best rule to overcome this problem. Thanks

```
*://*.google.com/*
*://drive.google.com/*
*-docs.googleusercontent.com/*
*://*.googleusercontent.com/*
https://drive.google.com/*
https://*.googleusercontent.com/*
```
![image](https://github.com/sblask/webextension-skip-redirect/assets/120319793/090cbc4f-15ff-4fdf-9e1a-9ae43cc5988e)

![image](https://github.com/sblask/webextension-skip-redirect/assets/120319793/1e235cd7-d369-4bad-8edc-7cfedcb23d10)

![image](https://github.com/sblask/webextension-skip-redirect/assets/120319793/092bb6ae-4714-4a35-9ff3-3bd2378fec0f)

**Comment by sblask** [comment]
You need to use the NO skip list.
