### ISSUE TITLE
Permanent Blacklist Addition Suggestions

### ISSUE THREAD

**Issue by eberhardweber** [sblask/webextension-skip-redirect#37]
Hello, 

Here are some of my additions to the Skip Redirect blacklist that avoid loops that I think are fairly universal for netizens, and should perhaps be added to the permanent list of blacklisted items:

/nonceSigner - Google Drive download redirect
/over18 - Reddit's Over 18 confirmation
/wp-login - WordPress admin login
/Shibboleth.sso and /Shibboleth-sso - [Shibboleth SSO service](https://www.shibboleth.net/) utilized by many universities - the format depends on version used, maybe?

Is it okay to suggest more of these if I happen to meet any? My thinking here is that the less problems a user faces out of the box, the better for the add-on.

**Comment by sblask** [comment]
I don't want to maintain a list for all the web. All the ones that are in the list are very generic and I won't add specific ones.
