### ISSUE TITLE
Infinite loop @ Tumblr

### ISSUE THREAD

**Issue by eberhardweber** [sblask/webextension-skip-redirect#41]
Here's an example URL of a Tumblr blog loop redirect that always goes to the same address:

http://t.umblr.com/redirect?z=https%3A%2F%2Fwww.humblebundle.com%2Fstore%2Fpromo%2Fhorror-sale%3Futm_source%3DFacebook%26utm_medium%3DLink%26utm_campaign%3DHorror_Sale_083117&t=YTNkYjZhZjVmNmRjN2RjOTJjYWE4ZWI0ZDgwYmQ0M2I2Yjc2ODA2MCxiNlNxdVVXYQ%3D%3D&b=t%3ALz353Gt9EBZmj6EJog4SOg&p=http%3A%2F%2Fblog.humblebundle.com%2Fpost%2F164829217715%2Fhorror-sale-humble-store-get-in-the-spooky-mood&m=1

**Comment by sblask** [comment]
Not for me? It goes straight to: http://blog.humblebundle.com/post/164829217715/horror-sale-humble-store-get-in-the-spooky-mood Any way, if you get problems, you should add the site to the blacklist.

**Comment by eberhardweber** [comment]
So you too have the same issue!

The link you posted is the website the link originates from. The address that should be redirected to should be https://www.humblebundle.com/store/promo/horror-sale which is housed in the early part of the URL.

**Comment by sblask** [comment]
Other people have real redirect loops, that's why I thought it's not an issue. Any way, nothing I can do, you've got to add it to the blacklist.
