### ISSUE TITLE
[Feature Request] A fork of Redirect Bypasser 

### ISSUE THREAD

**Issue by tunguyen6** [sblask/webextension-skip-redirect#42]
Skip Redirect works very well.
Check out Redirect Bypasser by Moises Lima. It seems to be abandoned, but it works uniquely and awesome.

I love its ability to extract links and the pop-up overlay which allow me to do whatever I want with them, e. g. to copy.
Can you fork features of it to your add-on? Thanks a lot.

https://github.com/mozlima/redirectbypasser
https://addons.opera.com/en/extensions/details/redirect-bypasser/
https://addons.mozilla.org/en-US/firefox/addon/redirectbypasser/

**Comment by sblask** [comment]
Not interested. I tried it before writing this add-on and I see how it avoids the problems Skip Redirect has, but I wanted an add-on where I don't have to check the urls that might be there. If I would have wanted the same behaviour, it would already be there.
