### ISSUE TITLE
A wrong redirection?

### ISSUE THREAD

**Issue by crssi** [sblask/webextension-skip-redirect#43]
Hello fellow @sblask 
URL [http://www.phoronix.com/scan.php?page=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+(Phoronix)](http://www.phoronix.com/scan.php?page=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+(Phoronix))
is redirected to [http://www.phoronix.com/scan.php?page=news_item](http://www.phoronix.com/scan.php?page=news_item)
but should not be. Actually should not be altered at all.
Or I have missed something?

Cheers

**Comment by sblask** [comment]
Not by Skip Redirect, there is nothing in the URL that could be redirected to. Maybe it's another one of your add-ons?

**Comment by crssi** [comment]
Ah... I have gave a bad example... sorry.

Please, try this one:
[https://outgoing.prod.mozaws.net/v1/9b92b9910062e5ab748313bf09ded6984cabce25a1ff2af6eb32f5f5fc3c9787/http%3A//www.phoronix.com/scan.php%3Fpage=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%253A%2BPhoronix%2B%28Phoronix%29](https://outgoing.prod.mozaws.net/v1/9b92b9910062e5ab748313bf09ded6984cabce25a1ff2af6eb32f5f5fc3c9787/http%3A//www.phoronix.com/scan.php%3Fpage=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%253A%2BPhoronix%2B%28Phoronix%29)
Redirection outcome should be:
[http://www.phoronix.com/scan.php?page=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+(Phoronix)](http://www.phoronix.com/scan.php?page=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+(Phoronix))

**Comment by sblask** [comment]
Seems like this page mixes encoded and not encoded URL values (`%3F` but also `&`) that's why it cuts off at the first not encoded value as it seems like the rest belongs to `https://outgoing.prod.mozaws.n...` no good way to handle this differently I think.

**Comment by crssi** [comment]
Thank you... in this case I wouldn't bother with it. I believe this is really a rare case.
You are champ.

Cheers
