### ISSUE TITLE
Adding /Login to the default blacklist ?

### ISSUE THREAD

**Issue by chmike** [sblask/webextension-skip-redirect#45]
I spent some time trying to find out why our SSO system didn't work. I forgot I installed skipRedirect.
Finally I found out that it was my skipRedirect that caused the problem and because the path was `/Login`. 
That is unfortunate. skipRedirect works very well to the point I forgot I installed it. 
Is it possible to add `/Login` to the blacklist ?

The SSO is used by all French institutions with [Shibboleth](https://www.shibboleth.net/). I don't know who is responsible to use an uppercase L for `/Login`.

**Comment by sblask** [comment]
I think the check should rather be case-insensitive in all cases...
