### ISSUE TITLE
Open full URL if notification link is clicked

### ISSUE THREAD

**Issue by Madis0** [sblask/webextension-skip-redirect#47]
If the URL is skipped and the notification appears to show it, why not let the user override the skip (open the redirecting link) when they click the original URL in notification? 

That would improve the usability by 

- making the notification actionable
- not having to disable the extension just for one URL

**Comment by sblask** [comment]
I am not a fan of having something happen when clicking on the notification itself. I often do that to hide notifications. I think having a button inside the notification would be good, but there is no Firefox support for button clicks yet and I would wait for that. Next question would be, open the URL in the same tab or in a new one? But the most critical question would be, when do I re-enable skipping? I guess I'd only disable skipping for this one tab and then wait till it's done loading?

**Comment by Madis0** [comment]
> I am not a fan of having something happen when clicking on the notification itself. I often do that to hide notifications. I think having a button inside the notification would be good, but there is no Firefox support for button clicks yet and I would wait for that.

I actually meant clicking the link inside the notification (as opposed to notification itself), but I guess the origin of the click can be hard to get, to understand that the user actually clicked the notification link and not some other link. Maybe you could add some javascript link to the notification to make the extension react?

> Next question would be, open the URL in the same tab or in a new one?

I'd open it in the same tab, as the goal is overriding the behaviour.

> But the most critical question would be, when do I re-enable skipping? I guess I'd only disable skipping for this one tab and then wait till it's done loading?

Yup, it should work just for that one link, it is meant to be temporary.
---
An alternative idea I just came up with would be improving just the context menu item "Copy last skipped URL" to work as "Open last skipped URL" instead.

**Comment by sblask** [comment]
There is nothing I can change about the notification. Buttons are the only way and as I said, it doesn't work in Firefox yet...

Adding it to the context menu might be a good way, because that would also be available when notifications are disabled.
