### ISSUE TITLE
Are any connections made to unfiltered links before sending to filtered links?

### ISSUE THREAD

**Issue by grauenwolfe** [sblask/webextension-skip-redirect#50]
@sblask  

Wanting to ask you directly if Skip Redirect makes any connections of any kind, in any way, to the unfiltered link before connecting to the filtered link? Other similar extensions seem to connect to the uncleaned tagged address first before the cleaned, intended address. Is this the case with Skip Redirect?

Please understand that this is in no way, even remotely intended to be accusatory, I just like to understand exactly what's running on my machine, that's all. Feel free to pitch in: https://github.com/ghacksuserjs/ghacks-user.js/issues/249
Thanks.

**Comment by sblask** [comment]
As I use a blocking onBeforeRequest (https://github.com/sblask/webextension-skip-redirect/blob/master/background.js#L187) no connection should be made unless the browser does some funny stuff.

**Comment by sblask** [comment]
Even if it seems so because the unfiltered URL appears in the location bar until the final page is loaded...

**Comment by grauenwolfe** [comment]
> Even if it seems so because the unfiltered URL appears in the location bar until the final page is loaded...

This was my primary reason for even questioning it. Great that you brought it up without even having been mentioned. Thanks for taking a second to clarify this.

**Comment by sblask** [comment]
I stumbled over this once and thought skipping is not working, but it's just that the location bar is updated when loading reached a certain point...
