### ISSUE TITLE
consider refining default blacklist?

### ISSUE THREAD

**Issue by atomGit** [sblask/webextension-skip-redirect#51]
in this case the redirect is not bypassed - i realize it's ultimately up to the user to configure the blacklist, but i'm wondering if the strings in the blacklist should be a bit more specific by default?

example URL: `https://outgoing.prod.mozaws.net/v1/14b631a713d4684de03418f5a14d81de35dbe188d42c5085568a0f37ad0b9940/https%3A//github.com/mrdokenny/Cookie-AutoDelete`

the redirection is allowed because of `/cookie` in the blacklist

i don't know how the strings in the blacklist typically appear in URLs, but perhaps this could all be a bit more specific to where, for example, `/cookie` becomes `/cookie/` or `/cookie[?&/]` or something?

**Comment by sblask** [comment]
I am aware it's not perfect, it's more of a best guess from my side and what I saw in other extensions. My thinking is that a URL that is not skipped is better than a broken webpage. Also the only real way to fix this would be data analysis on URLs collected from the users. I think we can agree that this is not desirable at all.

**Comment by crssi** [comment]
I am not sure yet, but after "same domain detection" has been implemented, I have removed all preconfigured "parameters" in blacklist with exception to my custom `rover.ebay.co`.
Up to now I have 0 breakages and the upper sample does skip and a workable way.
I will wait for a week or two of browsing, then will report back the results with any possible exceptions that comes along.
