### ISSUE TITLE
Could you please provide a privacy policy?

### ISSUE THREAD

**Issue by Atavic** [sblask/webextension-skip-redirect#52]
A project is asking for a privacy policy [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/236).

**Comment by sblask** [comment]
That's the second request for something from that project, I don't really see how Skip Redirect fits in there... Anyway, what should that policy look like? Skip Redirect does not connect to anywhere and hence can't track or forward anything to third parties.

**Comment by rekixex** [comment]
@sblask For example, like this:

https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/

> Privacy is a universal right.
> 
> Decentraleyes does not collect any data of any kind.

**Comment by sblask** [comment]
How about `This extension does not collect or send data of any kind to third parties`? Do you want to have it on Github (in the readme?) or on addons.mozilla.org or both?

**Comment by Atavic** [comment]
:+1: Seems great to me, sorry for bothering.

**Comment by Atavic** [comment]
👍 Seems great to me, sorry for bothering. If you add a line in the readme, that will be perfect.

**Comment by sblask** [comment]
Done.
