### ISSUE TITLE
Breaks Google reverse image search

### ISSUE THREAD

**Issue by mooms06** [sblask/webextension-skip-redirect#54]
Hi,

If I search an image on Google with [Reverse Image Search](https://addons.mozilla.org/fr/firefox/addon/image-reverse-search/) and with Skip Redirect activated, this will not works (open a new tab with the image).
It works if I deactivate Skip Redirect.
Firefox 56.0 x64 on Win7 x64.

Regards.

**Comment by sblask** [comment]
You'll have to add the URL to the blacklist.

**Comment by mooms06** [comment]
I made some tests, adding `/searchbyimage` in the blacklist is enough.
