### ISSUE TITLE
Popup is broken when Skip Redirect is put in the overflow menu.

### ISSUE THREAD

**Issue by kah0922** [sblask/webextension-skip-redirect#55]
If you put Skip Redirect in the overflow menu and then open it, this happens:
![Screenshot](https://i.imgur.com/7jQEy1A.png)

**Comment by sblask** [comment]
That's nothing I can do anything about, seems like a Firefox bug, would you mind filing one? https://bugzilla.mozilla.org/

**Comment by lhindir** [comment]
It seems to respect the width restriction now, but it's a little too much content for my monitor. Would it be possible to detect the window size and activate a scroll bar?

**Comment by lhindir** [comment]
Adding `overflow: auto;` to the [fieldset rules](https://github.com/sblask/webextension-skip-redirect/blob/89b42e5a5e477ca151c33e82c72a4e686c8ccccc/options/options.css#L9) should take care of the truncated content. Something like `max-height: 80vh;` (or some sensible pixel value) for the popup window would be nice too, so it doesn't go all the way to the bottom of the screen, which looks a bit weird. But I couldn't get that to work from the inspector.

**Comment by sblask** [comment]
@lhindir yeah, nah. Firefox just doesn't seem to follow normal CSS rules there and I am no interested in doing some hack that breaks the normal display of the popup.
