### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by xevidencex** [sblask/webextension-skip-redirect#56]
I have a problem opening google image results in encrypted mode..
& your addon couldn't help cause it leads me directly to the site
when i need the link google gives me including suggestions for
each image i open in a new tab.

(Ps: i need to always make searches using encrypted mode)

For exemple, for this search:
https://encrypted.google.com/search?hl=en&tbm=isch&q=Chocolate+truffle&nfpr=1&oq=&gs_l=#imgdii=yehk1XyGdGOk2M:&imgrc=hewqPbVUYaF6JM:

When i put single results to new tabs, i get this ex, this structure of page that i need:
https://www.google.com/imgres?imgurl=http%3A%2F%2Fimg.taste.com.au%2Fb8WVb5nl%2Ftaste%2F2016%2F11%2Fpeanut-butter-truffles-85908-1.jpeg&imgrefurl=http%3A%2F%2Fwww.taste.com.au%2Frecipes%2Fpeanut-butter-truffles%2F43ff7365-32af-47a0-b839-e1594a580f14&docid=0qyAUPxv1fl6aM&tbnid=x8JGyVDUhOBUPM%3A&vet=10ahUKEwj6rbax_fTWAhUFWhoKHR_FCvUQMwiFAigJMAk..i&w=3000&h=2000&hl=en&bih=865&biw=1400&q=Chocolate%20truffle&ved=0ahUKEwj6rbax_fTWAhUFWhoKHR_FCvUQMwiFAigJMAk&iact=mrc&uact=8

& for this search, i don't know how it happened, but it seems that google
prevents the display of search result in new tabs with its related thumbs
because i use pornographic terms:

https://encrypted.google.com/search?safe=off&hl=en&gl=us&pws=0&complete=0&tbm=isch&sa=1&q=porn&nfpr=1&oq=porn&gs_l=psy-ab.3...518346.518752.0.518950.0.0.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..0.0.0....0.2w0pLoeWKBU

When i open one image to a tab, i get the famous stupid  "redirect notice"
The previous page is sending you to https://blablah..
If you do not want to visit that page, you can return to the previous page.

https://www.google.com/imgres?imgurl=https%3A%2F%2Fbi.phncdn.com%2Fvideos%2F201706%2F03%2F118925191%2Foriginal%2F%28m%3Deaf8Ggaaaa%29%28mh%3DmGFVKRqc-iLGMgY3%2912.jpg&imgrefurl=https%3A%2F%2Fwww.pornhub.com%2Fview_video.php%3Fviewkey%3Dph593256d72c861&docid=HOH0p8sSpfKHpM&tbnid=knuEW42vwalbJM%3A&vet=10ahUKEwi9i92jgvXWAhXCrxoKHZPIBewQMwgpKAQwBA..i&w=320&h=240&hl=en&gl=us&safe=off&bih=865&biw=1670&q=porn&ved=0ahUKEwi9i92jgvXWAhXCrxoKHZPIBewQMwgpKAQwBA&iact=mrc&uact=8

How could i prevent this behavior ? without sending images i popen directly to their
origin site ?

here's my search engine in bookmarks:
https://encrypted.google.com/search?hl=en&gl=us&safe=off&pws=0&complete=0&tbs=ctr:us&tbm=isch&q=%s

**Comment by sblask** [comment]
I don't think you can, the URL looks the same to me, you can have either or. Always skipping or never skipping.

**Comment by xevidencex** [comment]
& do you know away i could force a site like pinterest or others, i'd
individually add to a script to open sites in the foreground & not new
windows ?
i don't want to use the firefox setting that applies to all sites, cause
some sites force users to open ads before opening the target link
