### ISSUE TITLE
Not working on mail.com

### ISSUE THREAD

**Issue by rayman89** [sblask/webextension-skip-redirect#57]
When clicking on links inside mail.com mails it goes to this and doesnt get redirected any idea why?

https://deref-mail.com/mail/client/18t8T7hb1X8/dereferrer/?redirectUrl=https%3A%2F%2Fgithub.com%2Fsienori%2FTab-Session-Manager%2Fissues%2F9%23issuecomment-336602667

**Comment by sblask** [comment]
Works for me. Something in your blacklist maybe that prevents skipping?

**Comment by rayman89** [comment]
My blacklist is the default one plus "?q="

**Comment by sblask** [comment]
As `?` is reserved in regular expressions, you have to escape it. Using `\?q=` should fix it.

**Comment by rayman89** [comment]
Thank you that fixed it.
