### ISSUE TITLE
Does not appear to work on open in new tab

### ISSUE THREAD

**Issue by bingo-the-pyro** [sblask/webextension-skip-redirect#58]
This is mostly for google search links.
Using CTRL+Click (or open in new tab) link still uses the redirect, when straight clicking it removes the redirect.
Also happens with other links more than not.

Firefox 56.0/Win 10 (v10.0.15063)

Let me know if you want more info :)

**Comment by sblask** [comment]
It's the other way around, click goes straight to a URL while using ctrl-click or middleclick adds an intermediate page. This is what Google does. So when clicking, Skip Redirect doesn't have to do anything, when using ctrl-click or middleclick, Skip Redirect can do something. So I assume you have something in your blacklist that prevents skipping on Google.
