### ISSUE TITLE
Page isn't redirecting properly

### ISSUE THREAD

**Issue by stelariusinfinitek** [sblask/webextension-skip-redirect#59]
[If I go to this page](https://hackernoon.com/neuralink-is-building-the-most-privacy-invasive-technology-of-our-time-3edf51ce448c), Firefox shows the error **The page isn’t redirecting properly** after many quick  attempts to load the page.

If I can help you somehow, tell me.

**Comment by sblask** [comment]
I think you copied the wrong link, there is no URL inside the URL and it just works fine. But if you do get this kind of problem, you have to add an entry to your blacklist.

**Comment by stelariusinfinitek** [comment]
If I turn off Skip Redirect, the site loads just fine. If I turn it on, this is what it's trying to do : 

![untitled](https://user-images.githubusercontent.com/18717816/32573409-9526351c-c4d6-11e7-9eb7-017e645c9da8.png)

**Comment by sblask** [comment]
Medium is doing some funny thing there. I've had the same problem and adding "medium.com" to the blacklist fixed it
