### ISSUE TITLE
Validate Blacklist content, and show the regular expression notation name in the Blacklist title of the preferences which is must be used 

### ISSUE THREAD

**Issue by woxcab** [sblask/webextension-skip-redirect#60]
Blacklist can content invalid regular expressions that's result in extension non-working.
Which is regex notation used for blacklist (PCRE, POSIX basic, POSIX extended, ...)? 
I suggest to:
* check validity of blacklist content before preferences saving. 
* show regex style name in the title of Blacklist: `(you may use ... regular expressions ...)`

**Comment by sblask** [comment]
Today I save after every keystroke and validating directly could make typing difficult. How to display errors would be difficult too. But I can imagine adding a validate button.

It's Javascript regular expressions, but if I'd add that, I feel I have to do some more explaining, which I don't want. Common patterns should be enough to express what you want, or what kind of expression do you want to use?

**Comment by woxcab** [comment]
> But I can imagine adding a validate button

It's acceptable too.

> It's Javascript regular expressions, but if I'd add that, I feel I have to do some more explaining, which I don't want

Even `(you may use JavaScript' regular expressions)` gets enough information about notation. So additional word can enhance title.
Do I right understand that blacklist lines always are interpreted as RegExp? Particularly, is the dot `.` symbol always interpreted as any symbol?

**Comment by sblask** [comment]
This is what happens: https://github.com/sblask/webextension-skip-redirect/blob/master/url.js#L102 exceptions is an array of the lines of either blacklist or whitelist.

**Comment by sblask** [comment]
I don't think I will do anything about this. If someone wants to add a validator, they can reopen this case.
