### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by alekksander** [sblask/webextension-skip-redirect#61]
extension doesn't work on Your example link from fx addon page.

what i get is:
```
File not found

Firefox can’t find the file at moz-extension://201a0bd9-ef88-4fea-bbaf-2c448ef3fc1d/http://www.mozilla.org/.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.
```

**Comment by sblask** [comment]
I don't know where you get that that URL from, but the example from https://addons.mozilla.org/en-GB/firefox/addon/skip-redirect/ is www.google.com/chrome/?i-would-rather-use-firefox=http%3A%2F%2Fwww.mozilla.org/

**Comment by alekksander** [comment]
please consider re–open.
with firefox **56.0.2** i get this:
![b1](https://user-images.githubusercontent.com/3148302/33011800-ea1bee0a-cdd6-11e7-962a-486e4ee969c0.png)

with latest firefox **nightly** i get:
![b2](https://user-images.githubusercontent.com/3148302/33011912-3f41dbba-cdd7-11e7-8156-791cec8eb46c.png)

**Comment by sblask** [comment]
For 56: you set Skip Redirect to whitelist mode, so unless the URL is on the whitelist, nothing will be done
Nightly: it's not stable and you can basically not use it for anything

**Comment by crssi** [comment]
I have Skip Redirect in blacklist mode and I get the same result as @alekksander. I am also on FF 56.
That is if I click the second link, you have posted [here](https://github.com/sblask/webextension-skip-redirect/issues/61#issuecomment-345545079).

**Comment by crssi** [comment]
As general observation: Something strange is happening, since quite a few update URL manipulation WEs doesn't work anymore on FF 56.
There is no error or complainings, it just doesn't do what is supposed to.

**Comment by sblask** [comment]
Works fine for me on 57. So maybe you've got something in your blacklist that causes it.

**Comment by alekksander** [comment]
ps.
normally whitelists are lists of pages, where extension is not working on.
blacklist — applies none but it,
whitelist — applies for all but it.

**Comment by sblask** [comment]
Nope, it's the other way around.

**Comment by alekksander** [comment]
well, not in other extensions like umatrix (and according to wikipedia). anyway, that's just digression, the main reason for this thread remains.
