### ISSUE TITLE
skipredirect_sblask_copy-last-source-url "Separator" Bug?

### ISSUE THREAD

**Issue by ImSpecial** [sblask/webextension-skip-redirect#63]
### New Issue Checklist (tick off like this: `[x]`)
[ x] I checked existing issues (open and closed) for possible duplicates

### What is your browser?
[ x] Firefox 57

### What is your operating system?
[x ] Windows 10

### Description (please include examples/screenshots where applicable)

Hi, I'm reporting that it seems your add-on creates a "separator" in the add-on Tabbar that doesn't get removed correctly when it should, and spills over onto other menus causing a double separator. 

Confused? Yeah me too, here is a relevant issue report for this because at first I thought it was a "CustomCSSforFx" issue, but the Dev there points to your add-on being the culprit, I'll take his word for it because he's the expert, there are pictures and whatnot that better explains what I mean in that issue too.

https://github.com/Aris-t2/CustomCSSforFx/issues/55

**Comment by sblask** [comment]
I do not create a separator (see https://github.com/sblask/webextension-skip-redirect/blob/master/background.js), it's Firefox doing it. I don't really understand what you are trying to achieve there, but if it's trying to hide disabled entries, why would the separator disappear when you are hiding the entry?
