### ISSUE TITLE
Skip Redirect Fail

### ISSUE THREAD

**Issue by MIkumoDelta** [sblask/webextension-skip-redirect#64]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates

### What is your browser?

- [ x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

**Comment by MIkumoDelta** [comment]
is not able to resolve this redirect:
http://2baksa.net/go/go.php?url=https://rg.to/file/56daed151c474b338aa8509b6a8a82db/ZD.Soft.Screen.Recorder.11.1.2.2b.rar.html

**Comment by sblask** [comment]
Works for me, I can click and it goes to rg.to... Check that you don't have some bad settings.
