### ISSUE TITLE
enterprise SSO

### ISSUE THREAD

**Issue by gcbw** [sblask/webextension-skip-redirect#65]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates

### What is your browser?

- [X] Firefox
- [X] Chrome

### What is your operating system?

- [X] Linux
- [X] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

company uses google suite for enterprise. And login is unified on yet another place: okta.com. While logging in with this extension enabled, i will see a notification of a redirect blocked for okta.com, and then the login flow will fail saying my browser doesn't support cookies.

If I disable the extension, I cannot see the redirect on the network panel's persistent log, nor on uMatrix log. It just shows the okta.com url directly. without a redirect, so i can't even suggest an exception or point to the actual url that fails.

I will try to add some logging to the extension (or let me know if there is one already) so i can report back what exactly fails. Leaving the issue noted here even without much info in case someone else beats me to it.

**Comment by sblask** [comment]
I need some URL to check for problems. I assume you click on some link to login? That you could just copy. Otherwise, you might have a problem when submitting a form? You should see the URL in the developer tools.

**Comment by gcbw** [comment]
the flow is: type a corporate email in the login box, bunch of redirect happens to share cookies.

one of them triggers the extension, i see the notification and then the redirects continues, but end up on a "enable cookies" support page.

what's the place where i can add some console.logs to figure this out? (still didn't even have time to checkout the source here)

**Comment by sblask** [comment]
Totally forgot, there is a context menu. If you right click on the toolbar icon, you can copy the last skipped URL, you can use that to create your exception (you possibly have to remove some user specific stuff...)

**Comment by gcbw** [comment]
aha! that's helpful. here is the url. 

```url
https://companyname.okta.com/app/google/abc/sso/saml?SAMLRequest=urlencodedstuff&RelayState=https%3A%2F%2Faccounts.google.com%2FCheckCookie%3Fcontinue%3Dhttps%253A%252F%252Fmail.google.com%252Fmail%252F%26service%3Dmail%26hl%3Den%26ss%3D1%26scc%3D1%26rm%3Dfalse%26checkedDomains%3Dyoutube%26checkConnection%3Dyoutube%253A181%253A0%26pstMsg%3D1%26osid%3D1
```

So it is not a google.com redirect after all, that's why i wasn't seeing it on the network logs.

**Comment by sblask** [comment]
So just add `https://companyname.okta.com/app/google/abc/sso/saml` to your blacklist and you should be done...

**Comment by crssi** [comment]
SAML is, like ADFS, authentication method widely used, specifically in business/enterprise environment and also in B2B situations for SSO (single sign on).
Since everybody is now running toward clouds, those will be used even more.

I would really suggest to add those to default.
Purpose to add:
`/adfs/ls/`
`/sso/`
`/saml/`

**Comment by gcbw** [comment]
feel kinda silly for not noticing earlier that there was a configuration page...  Glad it started a discussion to improve defaults  though.

**Comment by sblask** [comment]
Added, but I wait with a release until I am done with some other issues.
