### ISSUE TITLE
disq.us redirection not recognized?

### ISSUE THREAD

**Issue by Morg42** [sblask/webextension-skip-redirect#66]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [ ] Chrome
- [x] Vivaldi

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Links in disq.us comments are prefixed with http://disq.us/url?url= for obvious tracking. When clicking such a link (my example: the "pass.telekom.de" link in comment #10 by marcus05 on https://www.lawblog.de/index.php/archives/2017/11/30/tk-anbieter-muessen-in-der-rechnung-ueber-kuendigungsfristen-informieren/#disqus_thread) skip-redirect tells me it skipped a redirection, but the page stops on the disq.us link. It doesn't even load the redirection site, but shows a blank site with the long url (with redirect) in the address bar.

**Comment by sblask** [comment]
It's because disqus uses an encoded `:` in the URL. No way of knowing whether `:` should belong to disqus of telekom unless I added domain specific rules. I won't do that. It's one of the limitations of this extension.
