### ISSUE TITLE
Two simple question

### ISSUE THREAD

**Issue by Decopi** [sblask/webextension-skip-redirect#67]
Hi, two simple questions:

1) Is it possible to add to SkipRedirect other functions like "url-tracking-cleaning"?
If not, why do we need two add-ons for that? Please, does anybody know an add-on "all-in-one", tracking cleaning & redirecting/skipping urls?

2) Some skip/redirect add-ons are around or even less than 10 KiB size, with minimum system performance impact. Does add-on size/performance depend on quantity of rules/blocking or redirecting capabilities?

Thank you!

**Comment by sblask** [comment]
1. Yes, but I won't do it. It's better to have specialised extensions that do their thing really well.

2. It can. Depends on the implementation.

**Comment by Decopi** [comment]
@sblask thank you for your answer!

**Comment by Decopi** [comment]
@sblask Thank you Sebastian for your answers. Please, last questions:

a) I am comparing PureURL, NeatURL, ClearURLs and Untrackme.
Based on your knowledge, which one of these will be more complementary and less overlapping with SkipRedirect?

b) When I test some of these add-ons above, I see SkipRedirect working (the banner is popupping), showing overlapping of functions. May SkipRedict be a substitute of these other add-ons above mentioned?

c) Does SkipRedirect take care of the following filters?
utm_source, utm_medium, utm_term, utm_content, utm_campaign, utm_reader, utm_place, utm_userid, utm_cid, utm_name, utm_pubreferrer, utm_swu, utm_viz_id, ga_source, ga_medium, ga_term, ga_content, ga_campaign, ga_place, yclid, _openstat, fb_action_ids, fb_action_types, fb_ref, fb_source, action_object_map, action_type_map, action_ref_map, gs_l, pd_rd_r@amazon.*, pd_rd_w@amazon.*, pd_rd_wg@amazon.*, _encoding@amazon.*, psc@amazon.*, ved@google.*, ei@google.*, sei@google.*, gws_rd@google.*, cvid@bing.com, form@bing.com, sk@bing.com, sp@bing.com, sc@bing.com, qs@bing.com, pq@bing.com, feature@youtube.com, gclid@youtube.com, kw@youtube.com, $/ref@amazon.*, _hsenc, mkt_tok, hmb_campaign, hmb_medium, hmb_source

Thank you again!

**Comment by sblask** [comment]
a: I don know/use these, you have to see for yourself
b: see a
c: read the README, the examples you give have nothing to do with SkipRedirect
