### ISSUE TITLE
Block, Allow or Add Rule Request

### ISSUE THREAD

**Issue by Atechn** [sblask/webextension-skip-redirect#68]
### New Issue Checklist (tick off like this: `[x]`)

- [ X] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X ] Windows

### Description (please include examples/screenshots where applicable)
Had Redirect Control (Not Compatible for Optimum) which gave you the option to block, allow or add rule "POP OUT"
"Add Rule" was good and simple when purchases redirect to submit payment confirmed etc,
https://addons.mozilla.org/en-US/firefox/addon/redirect-control/
Also had a simpler Black List, White List Editor.
This would be great update in Skip Redirect. Other than that is works great.

**Comment by sblask** [comment]
I never used Redirect Control and can't comment on the functionality, but it sounds like something completely different from Skip Redirect.
