### ISSUE TITLE
Long title in menu bar

### ISSUE THREAD

**Issue by rugk** [sblask/webextension-skip-redirect#69]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

![grafik](https://user-images.githubusercontent.com/11966684/34250105-1e9523f4-e63c-11e7-823f-ccb5a42b5418.png)

That text is rather lengthy… Just remove the "openm settings" part. That is obvious (and if not, a title text may be more suitable)

**Comment by sblask** [comment]
The title is used as a tooltip on the toolbar icon and contains as much information as necessary. Not using the icon in the toolbar but keeping it in the menu is not a use case that is covered and I don't intend to change that.

**Comment by rugk** [comment]
Huh? What? That is what a user can do, so you can't say that's not a usecase. Don't know whether Mozilla has a recomemndation, but I think a tooltip and a text for a button are completly different things.

And, as said, it is very obvious this opens the settings. What should it do instead?

**Comment by sblask** [comment]
I didn't say it's not a use case. But it's one that I do not support. I use the toolbar icon to convey as much information as possible. Even if I changed the default title, whenever a redirect is skipped, the URL becomes part of the title too.
