### ISSUE TITLE
Sometimes skips, sometimes not....for same url scheme

### ISSUE THREAD

**Issue by StealthBlackOxide** [sblask/webextension-skip-redirect#70]
I tested the Addon with about 20 different "outgoing.prod.mozaws.net" links which lead to "github.com". These links are found on the Firefox Addon Store site like on https://addons.mozilla.org/de/firefox/addon/skip-redirect/

It's working on all Store sites except the ones which can be found here:
https://addons.mozilla.org/de/firefox/addon/cookie-autodelete/

Why isn't it working here? It's the same url scheme.

**Comment by sblask** [comment]
Because `/cookie` in on the default blacklist.
