### ISSUE TITLE
Breaks Google Translate and Bing Translator

### ISSUE THREAD

**Issue by ariasuni** [sblask/webextension-skip-redirect#73]
### New Issue Checklist

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description

When I try to translate a whole page, I’m redirected to the original page.

**Comment by crssi** [comment]
Add the following to blacklist:
```
microsofttranslator.com/
translate.google.com/
```

**Comment by ariasuni** [comment]
Is it not common enough to add to the blacklist? What’s your policy for inclusion as default exceptions?

**Comment by crssi** [comment]
I do not use those and I don't know how common this is. Also I am not the author of this fine extension, so its not my decision anyway.

I am using the next blacklist beside defaults:
```
cred_submit
/_login
/adfs/ls/
/sso/
/saml/
rover.ebay.co
/openid/
```

**Comment by sblask** [comment]
The question is not whether it's common enough, but whether I want to maintain the list. There are billions of websites where this extension might cause problems, I have other things to do than to update the extension for every one of them.

**Comment by ariasuni** [comment]
Maybe you should add a note somewhere, so that people know whether to report or not a bug about that kind of thing.
