### ISSUE TITLE
Tumblr embed URLs and affiliate links

### ISSUE THREAD

**Issue by amnesiac-kid** [sblask/webextension-skip-redirect#74]
Embed URLs from iframes: https://www.youtube.com/embed/w3jLJU7DT5E?feature=oembed&enablejsapi=1&origin=https://safe.txmblr.com&wmode=opaque gets redirected to https://safe.txmblr.com/.

Affiliate links: On [this blog post](https://staff.tumblr.com/post/146366872690/refreshing-our-community-guidelines) for example the [link to the Github commit](https://github.com/tumblr/policy/commit/691042ea2f1aea96a2081ed02e157ea5194b6eaf) gets redirected back to the blog post URL:

> https://t.umblr.com/redirect?z=https%3A%2F%2Fgithub.com%2Ftumblr%2Fpolicy%2Fcommit%2F691042ea2f1aea96a2081ed02e157ea5194b6eaf&t=OTY1OTcyMGNkNmE3ZTQ3MTIzMWIxYTYyYTE4NmNiZjExZjI5MDBmYSxObkxDTnpnNQ%3D%3D&b=t%3A0aY0xL2Fi1OFJg4YxpmegQ&p=https%3A%2F%2Fstaff.tumblr.com%2Fpost%2F146366872690%2Frefreshing-our-community-guidelines&m=0

**Comment by sblask** [comment]
Use your blacklist to avoid this kind of problem.
