### ISSUE TITLE
how to make whitelist for chart.googleapis.com?

### ISSUE THREAD

**Issue by FredThompsonII** [sblask/webextension-skip-redirect#75]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Here is an example URL which Skip Reject should ignore:

https://chart.googleapis.com/chart?cht=qr&chld=M|4&choe=UTF-8&chs=300x300&chl=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.mobile_infographics_tools.mydrive

This whitelist line should prevent parsing the URL...but it does not. Why? What whitelist will work?

*://chart.googleapis.com/*

**Comment by crssi** [comment]
Add it to the blacklist. Blacklist is the list where you tell SR to not to interfere.
I would maybe extend yours to `://chart.googleapis.com/chart?`

Cheers

**Comment by sblask** [comment]
I'd probably add `chart.googleapis.com/chart` to the blacklist.

**Comment by crssi** [comment]
@FredThompsonII do you mind telling me on which site you have/had this breakage?
Something crossed my mind and it will help me to see bigger picture.
