### ISSUE TITLE
Checkbox "Skip redirects for URLs with the same public domain" directive looks to be ignored

### ISSUE THREAD

**Issue by crssi** [sblask/webextension-skip-redirect#76]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Settings:
Radio button at "Skip all redirects except for URLs matching any of the lines in the blacklist"
Checkbox "Skip redirects for URLs with the same public domain" NOT checked.

Reproduce:
Open [http://www.dnsstuff.com](http://www.dnsstuff.com)
Enter for example `www.google.com` into DNSreport field on the form and hit ENTER.
The page should is redirected to [www.google.com](www.google.com) instead of not to be redirected and should open the [http://www.dnsstuff.com/tools#dnsReport|type=domain&&value=www.google.com](http://www.dnsstuff.com/tools#dnsReport|type=domain&&value=www.google.com)
It looks like the checkbox "Skip redirects for URLs with the same public domain" NOT checked is ignored.

**Comment by sblask** [comment]
It's not the same domain...

**Comment by crssi** [comment]
Hmmm... yesterday, my cafein level was way to low for the brain to function in the sanity area. ;)
Actually I had a tooth roots extraction at the dentist and my head was like a balloon after.
Nevertheless this one leads to another idea for improvement request but I will open a new request, where it will be more clearer and might make more sense.
