### ISSUE TITLE
Blacklist become invalid on Firefox 58

### ISSUE THREAD

**Issue by Crystal-RainSlide** [sblask/webextension-skip-redirect#77]
TestURL: http://127.0.0.1/?abp=https://github.com
Blacklist just become invalid and I'm can't find the reason anyway.
Something must changed in Firefox.

- Firefox Stable 58.0(x64)
- Windows x64

**Comment by sblask** [comment]
If you don't provide your blacklist, I can't help you. The default blacklist works fine.

**Comment by Crystal-RainSlide** [comment]
Well, all blacklists don't work on mine😶

**Comment by crssi** [comment]
Maybe something is wrong in your firefox profile. Did you try with a clean/new one?

**Comment by sblask** [comment]
There is only one blacklist. If you'd copy paste it I might be able to help, otherwise I'll close this issue.
