### ISSUE TITLE
Skip redirect does not work properly for links in Disqus comments.

### ISSUE THREAD

**Issue by devDoge** [sblask/webextension-skip-redirect#79]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Skip redirect does not work properly for links in Disqus comments.

For example, check there are 4 external links in [this comment](http://disq.us/p/1p89eul) and skip-redirect does its work by redirecting to the external website but it does not clear data properly which leads to "not found" pages in the respective external links.

From what I see, skip-redirect does not remove colon symbol **":"** and the data following it, which I think were added by disqus for some reason.

So I had to install the [disqus-undiirect](https://addons.mozilla.org/en-US/firefox/addon/disqus-undirect/) add-on and add disqus to the skip-redirect blacklist list.

It would be nice if you could fix this issue which would enable proper redirect support for links in disqus comments too. Thanks.

**Comment by sblask** [comment]
I won't add special rules for specific web sites...

**Comment by devDoge** [comment]
Its not for a specific website. Its for Disqus comment system.

Same issues exists for external links posted in Disqus comments in all websites. I added that videocardz.com link because you had asked for example.

**Comment by sblask** [comment]
Disqus is a specific website.
