### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Decopi** [sblask/webextension-skip-redirect#80]
Hi Sebastian! Please, a simple question:

UMatrix has an option called "Block all hyperlink auditing attempts". It is explaining in the following text:

"Hyperlink auditing is a mechanism which allow a party, any party, to be informed about which link a user clicked on a particular web page. It is essentially a tracking feature: it allows a web site, or any third-party to that web site, to be informed about which link you clicked on which one of its web pages. The sole purpose is to track your browsing activity."

Sebastian, my simple question is if this UMatrix option has the same function as SkipRedirect?

Thank you in advance!

**Comment by sblask** [comment]
No idea. It doesn't say what it actually does, so it may be easier to ask the author whether it's the same as SkipRedirect.

**Comment by hyperfekt** [comment]
Hyperlink auditing and tracking via redirects are orthogonal, so you would want to disable both.
For more information, take a look at https://html.spec.whatwg.org/multipage/links.html#hyperlink-auditing.
Essentially, hyperlink auditing will make your browser notify a server if you follow a link in addition to loading that link's target.

**Comment by sblask** [comment]
Alright, so it's not a UMatrix-only thing. Learned something there, thanks!
