### ISSUE TITLE
dont open url which is send in form 

### ISSUE THREAD

**Issue by unknow010** [sblask/webextension-skip-redirect#81]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)
- [X] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [X ] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

If you tip a valid URL in a Website (Search) Form,  the URL wont be submitted in Form, instead of this Firefox open the submitted URL in current Tab.
This only happens when your plugin is enabled.

**Comment by sblask** [comment]
Submitting a search form is not much different from clicking a link, so I can't add special handling to it. You'll have to add your search engine to the blacklist if you need this to work.
