### ISSUE TITLE
Tumblr redirect troubles.

### ISSUE THREAD

**Issue by Quizicalgin** [sblask/webextension-skip-redirect#83]
I'm aware that this is a duplicate of #71 however nothing in that post really tells me how to fix the problem, since I don't understand entirely what is being said in regards to coding.

None of the links in tumblr direct out properly with it enabled and I don't know how I'm supposed to add it to the blacklist ( as mentioned in #74 )or whitelist to stop it from happening.

*://*.tumblr.com/*

I tried putting that in whitelist but that doesn't seem to work, though mind you i made that from copy pasting the thing from the examples and replacing mozilla.org with tumblr. As for the blacklist I dunno how to add it, would i just be /tumblr? Again I don't know coding or expressions stuff like that. x.x;

Using firefox58 on windows10.

**Comment by sblask** [comment]
Add `tumblr.com` to the blacklist.

**Comment by Quizicalgin** [comment]
Thank you!
