### ISSUE TITLE
Support Firefox on Android.

### ISSUE THREAD

**Issue by gegemon2012** [sblask/webextension-skip-redirect#84]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] The issue is not about adding entries to the default blacklist

### What is your browser?

- [ ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Can you add support for the mobile version of Firefox in skip redirect?

**Comment by sblask** [comment]
If it doesn't work it mean that Firefox for Android is missing APIs that are required...

**Comment by gcbw** [comment]
Mind keeping this open as I plan to at least try to make it work? This can be a central place to keep the discussion/investigation going.

**Comment by Ben-Kaniobi** [comment]
> If it doesn't work it mean that Firefox for Android is missing APIs that are required...

Please add a note on the Github and addons.mozilla.org pages to clarify that this does not work on Android.

Or maybe it's possible through API to check if it's an Android device and then display a warning in the settings page?

**Comment by gcbw** [comment]
I was planning on picking this up as i assumed most of the android shortcomings are UI based.

if i check on https://github.com/mdn/browser-compat-data.git for all features and see if it is supported on firefox and firefox_android, there doesn't seem to be many items with `false` for android only: see https://gist.github.com/gcbw/b489b487843ca36b847a65b8fc606d3d

**Comment by sblask** [comment]
I had a quick look and it seems like the only thing missing that actually kills the whole extension is browser.contextMenus. There are more things that aren't supported and accessing them might cause exceptions, but they should not stand in the way of the basic functionality. So if the access to browser.contextMenus would be behind a check whether or not it's supported I'd expect everything but the toolbar icon to work. I have no time to work on this, but if you want to, be my guest...
