### ISSUE TITLE
What is happening here?

### ISSUE THREAD

**Issue by crssi** [sblask/webextension-skip-redirect#85]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Try to open [https://m.signalvnoise.com/hard-first-or-easy-first-a60fc0095577](https://m.signalvnoise.com/hard-first-or-easy-first-a60fc0095577)

Is this one redirecting to other page, which redirects back?

**Comment by sblask** [comment]
Nothing is happening, the page just loads for me?

**Comment by crssi** [comment]
Now its working here too.
Before the skip redirect prevented the loading, but now I am almost 100% sure that they must had have some server side problems and they have sorted it out soon after my issue posting.

Anyway, sorry for "spam" and thank you for your time

Cheers
