### ISSUE TITLE
Extension breaks the internet archive

### ISSUE THREAD

**Issue by Dostoi** [sblask/webextension-skip-redirect#86]
On the internet archive website, the extension redirect to the website you're looking the archive for and not the archives pages. Only happens on the main page of the internet archive.

https://archive.org/web/web.php

With the last version on firefox 58.0.2

**Comment by sblask** [comment]
THis has been discussed several times already. You have to add archive.org to the blacklist.

**Comment by Dostoi** [comment]
My bad sorry. But shouldn't it be added by default if it's known to break the website ?
