### ISSUE TITLE
Skipping to the wrong link

### ISSUE THREAD

**Issue by rayman89** [sblask/webextension-skip-redirect#87]
On tumblr there are links like this

 https://t.umblr.com/redirect?z=https%3A%2F%2Fyoutu.be%2FH1uFt5-GtRg&t=ZTg3ZWZhYTE2YjAwNzBjZTY4N2EwMDc5Nzk2MWFkODVkZmQzMTdlYix5TnF0N0tBMQ%3D%3D&b=t%3AC42mG1T7fchNY5mI2v5MEQ&p=http%3A%2F%2Ftofupandas.tumblr.com%2Fpost%2F169189329889%2Fyee-haw-heipos-final-chance&m=1

That instead of sending you to the youtube video https://www.yo utub e. com/watch?v=H1uFt5-GtRg&feature=youtu.be

they send you back to the same page 

http://tofupandas.tumblr.com/post/169189329889/yee-haw-heipos-final-chance

**Comment by crssi** [comment]
Add `t.umblr.com/redirect` to your Blaclist and your issue will wanish.

Cheers

**Comment by rayman89** [comment]
That's not a fix. Adding that url to the blacklist is just normal behavior of the page. The addon is not skipping the redirection which is what it was made for.

**Comment by sblask** [comment]
There are two URL in the redirect URL. It's not possible to know which one is the right one, so you have to blacklist.

**Comment by rayman89** [comment]
Well redirection is usually done to send you to an other domain so why not set the addon  to send you to the url with different domain or let the user choose where to go instead of completely ignoring the issue?
