### ISSUE TITLE
Context menu option to add to whitelist, or blacklist

### ISSUE THREAD

**Issue by 3d73a4a412** [sblask/webextension-skip-redirect#92]
### New Issue Checklist (tick off like this: `[x]`)

- [ X] I checked existing issues (open and closed) for possible duplicates
- [ X] I can reproduce the problem on the latest stable version (not nightly!)
- [ X] The issue is not about adding entries to the default blacklist

### What is your browser?

- [ X] Firefox
- [ ] Chrome

### What is your operating system?

- [ X] Linux
- [ ] Mac
- [ X] Windows

### Description (please include examples/screenshots where applicable)
First, this ext is great, by far the most effective/automated redirector. My request is actually because it works a bit too well :) and I am not figuring out the whitelist/blacklist patterns correctly... or its a bug :)

Ok, on startpage.com I use the proxy option so every link includes their proxy, problem is #1 I can't seem to add the correct info to the whitelist option, I have tried a variety like the following:
*://*.startpage.com/*
*://*.ixquick-proxy.com/*
The startpage links don't have the actual link in there so the redirector just takes me to the startpage homepage.

I have another issue with searx.me's proxy option, and their cache option (using archive.org) where I have tried 
*://*.archive.org/*
https://searx.me:3000/*
in these cases it seems to ignore what I have in the whitelist and redirects anyway... unless I am writing the patterns incorrectly.

FINALLY. I thought I'd add the suggestion of adding a context menu option that would parse a link and add it to either the whitelist or the blacklist? Anyway, it works quite well and believe me your work is appreciated!

**Comment by crssi** [comment]
Add the following to whitelist:
```
://startpage.com/
://.xquick-proxy.com/
://archive.org/
://searx.me:3000/
```
Cheers

**Comment by sblask** [comment]
I am not exactly sure what you are trying to do, but it sounds like you might have blacklist/whitelist mixed up. Please read the README to understand what they mean for this extension.
