### ISSUE TITLE
Feature request: an ability to set flags that tell the script to clean referral text that goes after them

### ISSUE THREAD

**Issue by thankyou-xx** [sblask/webextension-skip-redirect#93]
For example:
From this https://www.youtube.com/watch?v=YAse79s86Tt&list=GnsfoUh-8f98amoo235&index=9&t=87s
To this https://www.youtube.com/watch?v=YAse79s86Tt
by using some kind of flag that says "if a link has "www.youtube.com/watch?v=" in it, don't include text after 11th symbol that goes after that".

**Comment by sblask** [comment]
I am pretty sure there are other extensions that do that. Doesn't sound like it's in any way related to the core functionality of this extension.

**Comment by crssi** [comment]
@thankyou-xx you are looking for [NeatURL](https://addons.mozilla.org/firefox/addon/neat-url/) extension. ;)
