### ISSUE TITLE
Icon suggestions

### ISSUE THREAD

**Issue by vertigo220** [sblask/webextension-skip-redirect#95]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [n/a] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Waterfox

### What is your operating system?

- [x] Windows

### Description (please include examples/screenshots where applicable)

I think instead of the icon turning gray when disabled, it should turn red, to make it more obvious. Also, if possible, the "skip" label on it should show whenever on a tab that was redirected to the current URL. This would help both less tech-savvy users, making it more obvious of what might be the cause for a failed page load (I know there's a notification, but a visual cue on the icon to indicate it's the culprit would probably help), and users such as myself, in the event I might open several new tabs and not get to one of them for a while, only to find it didn't load right, and by then the notification is long gone.

**Comment by sblask** [comment]
I won't change the icon, especially since some people are very confused about blocking/skipping and I can image them to think red mean on.

As to the label, good idea, but too much work for me. If someone wants to pick this up I'll be happy to include it. Until then I close this.
