### ISSUE TITLE
Export/Import lists

### ISSUE THREAD

**Issue by vertigo220** [sblask/webextension-skip-redirect#96]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [N/A] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Waterfox

### What is your operating system?

- [x] Windows

### Description (please include examples/screenshots where applicable)

This is a minor one, since it's easy enough to just copy the lists into a text document, but the ability to export and import them might be worth considering. Definitely low priority, though.

**Comment by sblask** [comment]
If someone else wants to implement it, ok, but I won't do it.
