### ISSUE TITLE
Double redirect for WordPress subscription from gmx.net

### ISSUE THREAD

**Issue by FriendFX** [sblask/webextension-skip-redirect#97]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

I recently wanted to subscribe to a WordPress blog and received an email with the following confirmation link (note that I changed my keys and email address for privacy, but tried to keep the URL patterns intact):

https://deref-gmx.net/mail/client/RV25X0rqGXk/dereferrer/?redirectUrl=https%3A%2F%2Fpublic-api.wordpress.com%2Fbar%2F%3Fstat%3Dgroovemails-events%26bin%3Dwpcom_email_click%26redirect_to%3Dhttps%253A%252F%252Fsubscribe.wordpress.com%252F%253Fkey%253D0fb618e5ec04dd36ee50f42cc85f7f10%2526email%253Dmy.email%252540example.com%2526locale%253Den-gb%2526activate%253De42d67dde1422d2e8daadf2410888f5c%26sr%3D1%26signature%3D607ead5199c17060251242bfc204cff5%26user%3D0%26_e%3Da20suJIlGIgilTlOlZYIWcpjGIy32mNSbic1zFZ2IdQOmWF1CYGOibijjhyJNTXcgpmcCbZxIJWyUyyii6GIGyEJ6VfV1OI9NcflBu6b1nIIZGaGyYY3jIcbwIcb9ni5GIbcDbjQI9WiIi9lmw51IIbbBwbRt4lQyxiWFNejjhVlW1WZNcYhw2EsmdTIJNViW3II3In14wiSIi1lNTiWvMh6TAIINSice9afdIHYxhisvwkJIv9TZ3s29399iaIC6Cda3jTDztMbzUxMynIplw5eiV2CmbjIQwUbfFWbnvd16nWIX2NUvVtImddnD94iZLXyFE2jNhIwy2ROtp11MxFCiMNYJaJS9nOOU01C9YkblyVdFain6bIXIvtiiFjSgLR9WbNwINnJZifl9MvtwvxlfVi0aXWCcMMeOHe21YMLsicDLMysjXNNGl1cGOI6ZQG0sl5pxOtVVuFy5C9ZJpiYAzWiIsvGRlWycZidTiRREisXQJWMAMb21UCGb2Rticw6Yb6EiCcZFmFitOYiLmAmr6bWGsnQIJNm5bJLolbW%26_z%3Dz

This got converted by Skip Redirect to this:

https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https://subscribe.wordpress.com/?key=0fb618e5ec04dd36ee50f42cc85f7f10&email=my.email%40example.com&locale=en-gb&activate=e42d67dde1422d2e8daadf2410888f5c&sr=1&signature=607ead5199c17060251242bfc204cff5&user=0&_e=a20suJIlGIgilTlOlZYIWcpjGIy32mNSbic1zFZ2IdQOmWF1CYGOibijjhyJNTXcgpmcCbZxIJWyUyyii6GIGyEJ6VfV1OI9NcflBu6b1nIIZGaGyYY3jIcbwIcb9ni5GIbcDbjQI9WiIi9lmw51IIbbBwbRt4lQyxiWFNejjhVlW1WZNcYhw2EsmdTIJNViW3II3In14wiSIi1lNTiWvMh6TAIINSice9afdIHYxhisvwkJIv9TZ3s29399iaIC6Cda3jTDztMbzUxMynIplw5eiV2CmbjIQwUbfFWbnvd16nWIX2NUvVtImddnD94iZLXyFE2jNhIwy2ROtp11MxFCiMNYJaJS9nOOU01C9YkblyVdFain6bIXIvtiiFjSgLR9WbNwINnJZifl9MvtwvxlfVi0aXWCcMMeOHe21YMLsicDLMysjXNNGl1cGOI6ZQG0sl5pxOtVVuFy5C9ZJpiYAzWiIsvGRlWycZidTiRREisXQJWMAMb21UCGb2Rticw6Yb6EiCcZFmFitOYiLmAmr6bWGsnQIJNm5bJLolbW&_z=z

...which led to a site saying "Sorry, but the provided signature isn't valid." 

After disabling Skip Redirect, the correct link that ended up in my browser window looked as follows:

https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fsubscribe.wordpress.com%2F%3Fkey%3D0fb618e5ec04dd36ee50f42cc85f7f10%26email%3Dmy.email%2540example.com%26locale%3Den-gb%26activate%3De42d67dde1422d2e8daadf2410888f5c&sr=1&signature=607ead5199c17060251242bfc204cff5&user=0&_e=a20suJIlGIgilTlOlZYIWcpjGIy32mNSbic1zFZ2IdQOmWF1CYGOibijjhyJNTXcgpmcCbZxIJWyUyyii6GIGyEJ6VfV1OI9NcflBu6b1nIIZGaGyYY3jIcbwIcb9ni5GIbcDbjQI9WiIi9lmw51IIbbBwbRt4lQyxiWFNejjhVlW1WZNcYhw2EsmdTIJNViW3II3In14wiSIi1lNTiWvMh6TAIINSice9afdIHYxhisvwkJIv9TZ3s29399iaIC6Cda3jTDztMbzUxMynIplw5eiV2CmbjIQwUbfFWbnvd16nWIX2NUvVtImddnD94iZLXyFE2jNhIwy2ROtp11MxFCiMNYJaJS9nOOU01C9YkblyVdFain6bIXIvtiiFjSgLR9WbNwINnJZifl9MvtwvxlfVi0aXWCcMMeOHe21YMLsicDLMysjXNNGl1cGOI6ZQG0sl5pxOtVVuFy5C9ZJpiYAzWiIsvGRlWycZidTiRREisXQJWMAMb21UCGb2Rticw6Yb6EiCcZFmFitOYiLmAmr6bWGsnQIJNm5bJLolbW&_z=z

Looks like Skip Redirect decoded too many characters of the original URL, but I'm not sure this can be easily avoided, unless there is a universal "stop decoding here" marker (in this case I could imagine it being the first *decoded* `https://`).

**Comment by sblask** [comment]
This looks like an actual problem, but I don't know when I will have time to look into it. You can try to blacklist `public-api.wordpress.com`

**Comment by FriendFX** [comment]
Thanks for the update. Meanwhile, I have come across another example:

Original URL:

https://deref-gmx.net/mail/client/dJcqFOKsYML/dereferrer/?redirectUrl=http%3A%2F%2Flink.indiegogo.com%2Fclick%2Fe9edebf7b68c712005fefc17%2Fw01Z1aNBrUa20bRXRYGTjmZ5oMYTVVG9OvcdJGQnUmbcdhjZlGcd2TTZ55dYHpVWeRgh30MaUQodVZLYzMTeNFhLXThD1VpV6BNlzSmRMl1qNrcZTXT1ZMWMMV03Rl3MTWcO0O1ZjhYvFbl2YbbLRfjuclRR3lzgzV9Wodhj2bwvURTm1TpQb3YNy1wl1W93JbbaL3HDjEvZaQFZTL3ZVGvWkldY35VW50SFhmZeWWxRZ5WMQWnSbbF3GM0WdTkHNR2phzhNH5%2Fb0855176af4c4b3Bf4330f73383e34d8b

Should redirect to:

http://link.indiegogo.com/click/e9edebf7b68c712005fefc17/w01Z1aNBrUa20bRXRYGTjmZ5oMYTVVG9OvcdJGQnUmbcdhjZlGcd2TTZ55dYHpVWeRgh30MaUQodVZLYzMTeNFhLXThD1VpV6BNlzSmRMl1qNrcZTXT1ZMWMMV03Rl3MTWcO0O1ZjhYvFbl2YbbLRfjuclRR3lzgzV9Wodhj2bwvURTm1TpQb3YNy1wl1W93JbbaL3HDjEvZaQFZTL3ZVGvWkldY35VW50SFhmZeWWxRZ5WMQWnSbbF3GM0WdTkHNR2phzhNH5/b0855176af4c4b3Bf4330f73383e34d8b

...but doesn't (I don't know the actual destination URL as the server re-directed me to a generic error page).

**Comment by FriendFX** [comment]
In other news, I tried to add the [first example to the tests](https://github.com/FriendFX/webextension-skip-redirect/blob/c9ef8df9573c7a1343b28ffed978e0ff8edfbf20/test-url.js#L156) but I think I failed to use your function correctly as the result doesn't match what I [had reported](https://github.com/sblask/webextension-skip-redirect/issues/97#issue-323857795).

**Comment by sblask** [comment]
The GMX redirect page is definitely skipped. It is one of the main reasons I started working on this extension...

**Comment by sblask** [comment]
I don't think I will find the time to look into the double decode problem anytime soon, so I'll just close. If someone else wants to pick it up, please re-open. Regarding the second example, I get redirected to what you posted, but then indiegogo redirects to its homepage. I got the URL you get initially redirected to by using Chrome's DevTools (ctrl-shift-i).
